### ISSUE TITLE
Ledger: System can’t update the selection.

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#10]
Finance > Maintenance > Chart of Acc > add New > Select Account Type = Asset > Select Sub Level 1 “Fixed Assets at Cost” > system can’t update the selection. It remained as “Other Assets”  
![image](https://user-images.githubusercontent.com/47977411/53339530-97908880-3941-11e9-8b16-076d2caaabc2.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9761

**Comment by jessa21** [comment]
Checked
