### ISSUE TITLE
Stock Count 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#103]
![image.png](https://images.zenhubusercontent.com/5c77b35204004e3ba48b7f83/5ea25d62-73dd-44fe-ba5a-0a81b941c3ad)

**Comment by ZawZawThein** [comment]
Pages:
 Areas/Inventory/A21IMStockCounting/Content.cshtml
 Areas/Inventory/A21IMStockCounting/Index.cshtml
 Areas/Inventory/A21IMStockCounting/Script.cshtml
`
Controller:  Areas\Inventory\Controllers\A21IMStockCountingController.cs

**Comment by ZawZawThein** [comment]
For Report: 
### A2000ERP\A2000ERP\Controllers\PreviewReportController.cs

Repx file: 

1. StockCountWorkSheet.repx
2. IMReCount1sheet.repx
3. IMReCount2sheet.repx
4.R21IMStockVariance.repx

### Dataset: Report_Dataset\Inventory\R21IMStockCountSheet.xsd
Dataset: Report_Dataset\Inventory\R21IMStockVariance.xsd

**Comment by ZawZawThein** [comment]
Alter Procedure R21IMStockVariance
 @StockDate datetime,
 @Warehouse varchar(50)
AS     
BEGIN  

SELECT DISTINCT MSTProduct.Product, 
isnull(MSTProduct.PName,'''') AS Name,
MSTProduct.StockUnit, MSTProduct.Class1, MSTProduct.Brand,
R21IMStockVarianceActQuantity.Quantity AS Quantity,
A21IMWarehouseStock.Warehouse, A21IMWarehouseStock.Count, A21IMWarehouseStock.Recount1,
A21IMWarehouseStock.Recount2, A21IMWarehouseStock.FlagRecount1,
A21IMWarehouseStock.FlagRecount2,
--IIf([FlagRecount2],[Recount2],IIf([FlagRecount1],[Recount1],[Count])) AS QuantityCounted,
R21IMStockVarianceActQuantity.StockValue
--IIf([Quantity]=0,0,R21IMStockVarianceActQuantity.StockValue/[Quantity]) AS AvgUnitPrice

FROM MSTProduct INNER JOIN A21IMWarehouseStock ON 
MSTProduct.Product = A21IMWarehouseStock.Product
AND MSTProduct.Company = A21IMWarehouseStock.Company 
LEFT JOIN dbo.R21IMStockVarianceActQuantity( @StockDate, @Warehouse) as  R21IMStockVarianceActQuantity

ON A21IMWarehouseStock.Product = R21IMStockVarianceActQuantity.Product

WHERE (((A21IMWarehouseStock.Warehouse)='B2B') AND ((MSTProduct.Type)='I'))

End

**Comment by ZawZawThein** [comment]
CREATE function [dbo].[R21IMStockVarianceActQuantity ]
(
 @StockDate datetime,
 @Warehouse varchar(50)
)
returns table
return

SELECT DISTINCT A21IMTransactionDetail.Product,
A21IMTransactionDetail.Warehouse, 
dbo.RDX(Sum([ReceiptQuantity]-[IssueQuantity]),4) AS Quantity,
dbo.RDX((IIf([ReceiptQuantity] Is Null,0,[ReceiptQuantity])*IIf([Rate] Is Null,0,[Rate])
-(IIf([IssueQuantity] Is Null,0, [IssueQuantity])*IIf([Cost] Is Null,0,[Cost])))
*IIf([ExchangeRate] Is Null,1,[ExchangeRate]),4) AS StockValue

FROM (A21IMTransactionDetail INNER JOIN A21GLTransactionHeader 
ON (A21IMTransactionDetail.TrnNo = A21GLTransactionHeader.TrnNo) AND 
(A21IMTransactionDetail.TrnType = A21GLTransactionHeader.TrnType) AND 
(A21IMTransactionDetail.Company = A21GLTransactionHeader.Company)) 
INNER JOIN A21IMWarehouseStock ON (A21IMTransactionDetail.Company = A21IMWarehouseStock.Company) 
AND (A21IMTransactionDetail.Product = A21IMWarehouseStock.Product) 

AND (A21IMTransactionDetail.Warehouse = A21IMWarehouseStock.Warehouse)
WHERE (((A21GLTransactionHeader.TrnDate)<= @StockDate)
AND ((A21IMTransactionDetail.Warehouse)= @Warehouse))

GROUP BY A21IMTransactionDetail.Product, A21IMTransactionDetail.Warehouse,
ReceiptQuantity,Rate,IssueQuantity,Cost,ExchangeRate

**Comment by zeusa2000** [comment]
Hi @ZawZawThein can i close this issue now? as per checking the page is currently active as of the moment. Kindly find attached file for your reference. 
![Stock Count Test- Working(WebErp)](https://user-images.githubusercontent.com/51438852/59176052-72d7be00-8b8a-11e9-98d3-aa5892ba6c8e.png)

**Comment by zeusa2000** [comment]
Issue moved to [a2000-erp-team/Job-Order-PMS #18](https://github.com/a2000-erp-team/Job-Order-PMS/issues/18) via [**ZenHub**](https://www.zenhub.com/)
