### ISSUE TITLE
Stock Transfer with Transit 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#104]
![image](https://user-images.githubusercontent.com/47977411/56643330-07a25d00-66ac-11e9-96dd-e78ec5754c52.png)

**Comment by zeusa2000** [comment]
As per testing the module is currently working and do the sample transaction and its properly execute and saved.


![image](https://user-images.githubusercontent.com/51438852/59573864-8aadc580-90e7-11e9-8f6e-688062c89155.png)

![image](https://user-images.githubusercontent.com/51438852/59573939-cb0d4380-90e7-11e9-92b8-26de05b358ce.png)

![image](https://user-images.githubusercontent.com/51438852/59573943-d1032480-90e7-11e9-8e46-a42d51e41555.png)
