### ISSUE TITLE
Product Main Cat 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#105]
http://a21.sg:94/Inventory/frmPdaISTransaction/430
![image](https://user-images.githubusercontent.com/47977411/56643569-7384c580-66ac-11e9-96fa-755526d4d36c.png)

**Comment by ZawZawThein** [comment]
It is duplicate menu. I remove this menu description.
We can test ProductMainCategory page in this link.

### Go> Warehouse > Admin > Master Settings>  ProductMainCat
**http://a21.sg:94/Inventory/SUProductMainCategory/320**

**Comment by ZawZawThein** [comment]
### Changeset 10246

IF  EXISTS(SELECT 1 FROM pref_language_values  where menu_category_id = 6 and menu_id = 430 and lang_id = 10 )
BEGIN
	update pref_language_values set value =null where menu_category_id = 6 and menu_id = 430 and lang_id = 10
END

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/59181459-ff3dad00-8b99-11e9-90e8-6647a3d580c4.png)
As per checking product main cat is not under Warehouse=>Admin=>Operations. Currently under working

**Comment by zeusa2000** [comment]
Currently working under Warehouse=>Admin=>Master Settings=>ProductMainCat. Will close the issue.
