### ISSUE TITLE
SAL-POS-GDS-[(A) Add a new menu for Global Discount Setting under the Setting submenu. (B) In the Global Discount Setting, add a new button for Category to setup the types of categories, however “Global” will be a by default category in this setup table and is un-editable. (C) Categories with Day of Week will appeared on that specific day from the pop up window for user to apply the discount. (D) Delete the extra column.]

### ISSUE THREAD

**Issue by A2000-ISTEAM** [a2000-erp-team/WEBERP#1069]
![image.png](https://images.zenhubusercontent.com/5e8e8265b7c1d9906c2bbc2c/91260e69-ae58-47db-aac7-bbe630adc5a0)

![image.png](https://images.zenhubusercontent.com/5e8e8265b7c1d9906c2bbc2c/e55bf6b9-5b29-431f-8c7d-4e14c19b1ee0)

101.   (A) Add a new menu for Global Discount Setting under the Setting submenu. (B) In the Global Discount Setting, add a new button for Category to setup the types of categories, however “Global” will be a by default category in this setup table and is un-editable. (C) Categories with Day of Week will appeared on that specific day from the pop up window for user to apply the discount. (D) Delete the extra column.

**Comment by A2000-ISTEAM** [comment]
A) Done in 94, 
B) Done in 94
C) Not Done in 94. Student promo category doesn't appear in pop up window
D) Done in 94.

**Comment by A2000-ISTEAM** [comment]
Not done in SSVP

**Comment by RekhaBhatt** [comment]
it is because of License file. this module name is missing in license file.
