### ISSUE TITLE
Error Msg " Please adjust your number setting"

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#107]
When click ADD button, system prompt msg as below:
![image](https://user-images.githubusercontent.com/47977411/56644003-674d3800-66ad-11e9-9dac-e07e1cbc88fd.png)

I set up the transaction number already. I am not sure why the mentioned system message prompt out. 
How do we disable this msg?

**Comment by ykauniqe** [comment]
please should setup IM transaction in Document Numbering Scheme in System Utilities. After that,
warning message popup will be gone in screen.

**Comment by ykauniqe** [comment]
![documentnumbering](https://user-images.githubusercontent.com/47884745/57284345-feb38180-70d6-11e9-997d-c2b34e27f207.png)

**Comment by zeusa2000** [comment]
Can add now without error message pop out.

![image](https://user-images.githubusercontent.com/51438852/59419630-e33a4580-8dfd-11e9-89e6-3f7af6d2fa28.png)

![image](https://user-images.githubusercontent.com/51438852/59419669-f77e4280-8dfd-11e9-826b-41bc563e85a1.png)
