### ISSUE TITLE
Stock Kit Assembly /Disassembly

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#109]
1 - "Confirm" button is out of box margin 
2 - Production Order Details column is not shown completely 

Stock Kit Assembly 
http://a21.sg:94/Inventory/A21IMKitAssembly/90
![image](https://user-images.githubusercontent.com/47977411/56647139-82bb4180-66b3-11e9-96d3-625ab4ee99ac.png)

Stock Kit Disassembly 
http://a21.sg:94/Inventory/A21IMKitDisassembly/100
![image](https://user-images.githubusercontent.com/47977411/56647852-bfd40380-66b4-11e9-96a9-89121a761810.png)

Clarity: 
![image](https://user-images.githubusercontent.com/47977411/56647389-f2c9c780-66b3-11e9-9b2f-12f82dad454f.png)

**Comment by ZawZawThein** [comment]
Changeset 10186
Affected file: Areas\Inventory\Views\A21IMKitAssembly\Content.cshtml

**Comment by zeusa2000** [comment]
Kit Assembly transaction the confirm button is already aligned. See attached image.

![image](https://user-images.githubusercontent.com/51438852/59320718-e5b77500-8d01-11e9-8258-c993c2e3d473.png)

Kit Disassembly transaction the confirm button is not yet align. See attached image.

![image](https://user-images.githubusercontent.com/51438852/59320791-2a431080-8d02-11e9-953c-7c2b12d258ea.png)

**Comment by ZawZawThein** [comment]
Changeset 11379

**Comment by zeusa2000** [comment]
The confirm button now is aligned.

![image](https://user-images.githubusercontent.com/51438852/62512881-76b35400-b84c-11e9-9665-08b4c3514d7c.png)
