### ISSUE TITLE
 Ledger:  COA - Sub-Level 2 can’t update 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#11]
> SelectSub-Level 2 > system can’t update “Factory Equipment” 

![image](https://user-images.githubusercontent.com/47977411/53339623-d9213380-3941-11e9-82b9-cb2592c0260b.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9761

**Comment by jessa21** [comment]
Checked.
