### ISSUE TITLE
Save button not working

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#112]
http://a21.sg:94/SystemManager/MSTUser/30
![image](https://user-images.githubusercontent.com/47977411/56884803-75c89480-6a9d-11e9-8a34-38ea1b20141c.png)

**Comment by ykauniqe** [comment]
after clicking the Edit button first, save button will be working.

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/59180114-a91b3a80-8b96-11e9-9f4d-06707258a0de.png)
As per testing can save the transaction but do the edit button first then select which transaction need to grant an access then click the save button.
