### ISSUE TITLE
WEB ERP - PRODUCT IMPORT

### ISSUE THREAD

**Issue by A2000-ISTEAM** [a2000-erp-team/WEBERP#1121]
![image.png](https://images.zenhubusercontent.com/5e8e8265b7c1d9906c2bbc2c/9040f92d-f9e1-4803-9e34-865f411859d4)

Pname – did not show the information as per Excel file

**Comment by EiEiZin** [comment]
Pname empty issue is due to naming case sensitive. this name must be "PName".
Not to be occured this issue, we updated the system to download formatted template.

![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/c65f1d17-1c0b-4daf-8e1d-624e4503d2c8)
