### ISSUE TITLE
Supplier Data Import

### ISSUE THREAD

**Issue by A2000-ISTEAM** [a2000-erp-team/WEBERP#1125]
![Data-Import-Supplier.png](https://images.zenhubusercontent.com/5e8e8265b7c1d9906c2bbc2c/c2ac7200-a11c-4c4e-a73e-5640bbc70afc)

Cname is empty

**Comment by EiEiZin** [comment]
Cname empty issue is due naming case sensitive. this name must be "CName".
For avoid this case, we updated the system to download formatted template.

![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/2c865377-b40b-4761-b64c-4fb99c0fed0a)
