### ISSUE TITLE
EmailSetting

### ISSUE THREAD

**Issue by ZawZawThein** [a2000-erp-team/WEBERP#119]
Setup EmailSetting under SystemManager 
note. as same as Clarity Version

**Comment by ZawZawThein** [comment]
Controller file Location:
Areas\SystemManager\Controllers\EmailSettingController.cs

Views file:

- Areas\SystemManager\Views\EmailSetting\Content.cshtml
- Areas\SystemManager\Views\EmailSetting\EmailSetting_Script.cshtml
- Areas\SystemManager\Views\EmailSetting\Index.cshtml

DataSet: Report_Dataset\EmailSetting\EmailSetting.xsd

Adapter time out:
Areas\SystemManager\Models\EmailSettingAdapterTimeOut.cs

**Comment by zeusa2000** [comment]
Tried to do an email testing and receive thru gmail.

![image](https://user-images.githubusercontent.com/51438852/62912048-1cb90e00-bdb9-11e9-8046-9d3f6ba6cb63.png)
