### ISSUE TITLE
Ledger: COA Mapping

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#12]
Select drop down list > select any one of level 1 / level 2 / level 3 ….. > system can’t update the selection 

![image](https://user-images.githubusercontent.com/47977411/53339703-066de180-3942-11e9-90d0-7b8153d28548.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9761

**Comment by jessa21** [comment]
Checked.
