### ISSUE TITLE
Ledger: COA- Cannot update sub-level for sub lever 1 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#13]
Add New Sub-Level for Sub Level 1 > Can’t update the new Sub Level . 
![image](https://user-images.githubusercontent.com/47977411/53339750-23a2b000-3942-11e9-8b43-38145e49d933.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9765

**Comment by jessa21** [comment]
Checked.
