### ISSUE TITLE
Finance -> Ledger -> Operations -> Year Ending

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#15]
![2019-02-26_08h54_30](https://user-images.githubusercontent.com/47963293/53379173-824c4600-39a3-11e9-85f0-c8f4fd0bc94f.png)

**Comment by ZawZawThein** [comment]
![yearending](https://user-images.githubusercontent.com/47886841/53486150-58377880-3ab6-11e9-8c28-d15a5636e6dd.png)

Please try again. It can test.

**Comment by ErwinMetra** [comment]
Now, can see.
