### ISSUE TITLE
Finance -> Ledger -> Operations -> Enter GL Opening Balance

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#16]
![2019-02-26_08h55_41](https://user-images.githubusercontent.com/47963293/53379198-a3ad3200-39a3-11e9-9ca4-ceac86f23cc4.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9846

**Comment by zawuniqesolutions** [comment]
Changeset 9900

**Comment by ErwinMetra** [comment]
Now, the preview only takes less than 5 seconds.
