### ISSUE TITLE
PROCUREMENT=>PURCHASE=>Reports&Queries=>Purchase Order Tracking by PO Type(Report Under Construction).

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#164]
Purchase Order Tracking by PO Type(Report Under Construction).

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/abde393d-9657-405d-a08e-7e32cb14003a)

**Comment by Aungyetun991990** [comment]
Menu Missing

**Comment by zeusa2000** [comment]
Can able to view now the report.

![image](https://user-images.githubusercontent.com/51438852/84483611-29a1d900-accc-11ea-9654-df9b88433190.png)
