### ISSUE TITLE
Finance -> Ledger -> Operations -> Enter GL Opening Balance

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#17]
![2019-02-26_08h56_12](https://user-images.githubusercontent.com/47963293/53379231-c63f4b00-39a3-11e9-998c-fd1250aadd2e.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9790

**Comment by ErwinMetra** [comment]
Now, allows selection of Currency.
