### ISSUE TITLE
Sales=>Billings=>Reports&Queries=>Master Listing - Customers (With Delivery Address) Repx Enhancement.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#171]
Enhancement on the repx for Master Listing - Customers (With Delivery Address).

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/c6e07cc2-7343-49e7-87d3-eaca4a41433d)

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/b1cf4fff-7eb9-481f-9cca-757c06d29d5d)

**Comment by ZawZawThein** [comment]
fix R21MSTCustomerDelAdd.repx

**Comment by zeusa2000** [comment]
Same with clarity report.

![image](https://user-images.githubusercontent.com/51438852/62529020-67460200-b870-11e9-9a31-b6bdcd46cac9.png)
