### ISSUE TITLE
Sales=>Billings=>Report&Queries=>Sales Order Listing (Pending,XLS Format) Report Under Construction.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#175]
Sales Order Listing (Pending,XLS Format) Report Under Construction.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/80501bd6-484e-47f1-948b-279108d4e99f)

**Comment by zeusa2000** [comment]
Report need to enhance xls format should be same like clarity.

![image](https://user-images.githubusercontent.com/51438852/62920186-8fd17d00-bdd7-11e9-99e6-40b622f06438.png)

**Comment by ZawZawThein** [comment]
Changeset: 11616

**Comment by zeusa2000** [comment]
As per checking matched in the current weberp format report.


![image](https://user-images.githubusercontent.com/51438852/63244025-d408c580-c28e-11e9-9f2a-c4e32aa74378.png)
