### ISSUE TITLE
Sales=>Billings=>Report&Queries=>Customer Invoice Listing (With DO & Order) Report Under Construction.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#177]
Customer Invoice Listing (With DO & Order) Report Under Construction.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/ec7c8283-1c5f-4ecb-ae9b-81d076b25a69)

**Comment by ZawZawThein** [comment]
need to run store procedure 

CREATE PROCEDURE [dbo].R21OPInvoiceOnOrderDoNew    
	@Trntype	NVARCHAR(15) = NULL,
	@TrnNoFrom	NVARCHAR(15) = NULL,
	@TrnNoTo NVARCHAR(15) = NULL,
	@RefNofrom	NVARCHAR(15) = NULL,
	@RefNoTo NVARCHAR(15) = NULL,
	@Date_From date = null,   
	@Date_To date = null,
	@CustCodeFrom	NVARCHAR(20) = NULL,
	@CustCodeTo NVARCHAR(20) = NULL
AS     
BEGIN 
Select [Transaction],Company, TrnType, TrnNo,Code, CName, DocNo, TrnScreen, TrnGrp, SCustomer,TrnDate, SalesPerson
from
(
SELECT DISTINCT dbo.GetTransaction(A21OPInvoiceHeader.TrnType,A21OPInvoiceHeader.TrnNo) AS [Transaction],
A21GLTransactionHeader.Company, A21GLTransactionHeader.TrnType, A21GLTransactionHeader.TrnNo,
MSTCustomerSupplier.Code, MSTCustomerSupplier.CName, A21GLTransactionHeader.DocNo, 
A21GLTransactionHeader.TrnScreen, A21GLTransactionHeader.TrnGrp, MSTCustomerSupplier.SCustomer,
A21GLTransactionHeader.TrnDate, A21GLTransactionHeader.SalesPerson

FROM (MSTCustomerSupplier INNER JOIN (A21GLTransactionHeader INNER JOIN A21OPInvoiceHeader ON (A21GLTransactionHeader.Company = A21OPInvoiceHeader.Company) AND
(A21GLTransactionHeader.TrnType = A21OPInvoiceHeader.TrnType) AND (A21GLTransactionHeader.TrnNo = A21OPInvoiceHeader.TrnNo)) ON (MSTCustomerSupplier.Company = A21GLTransactionHeader.Company) 
AND (MSTCustomerSupplier.Code = A21GLTransactionHeader.Code)) INNER JOIN  FullUserAccess(1) ON (MSTCustomerSupplier.Company = FullUserAccess.Company) AND (MSTCustomerSupplier.Code = FullUserAccess.Code)

WHERE A21GLTransactionHeader.TrnScreen in ('CE','CB' ,'CI','CC')
AND A21GLTransactionHeader.TrnDate >=@Date_From AND A21GLTransactionHeader.TrnDate <=@Date_To 
--AND A21GLTransactionHeader.TrnDate >='2017/04/01' AND A21GLTransactionHeader.TrnDate <='2017/04/05' 
AND  (ISNULL(@TrnType, '') = '' OR A21OPInvoiceHeader.TrnType = @Trntype)
AND ((ISNULL(@TrnNoFrom, '') = '' OR A21OPInvoiceHeader.TrnNo >= @TrnNoFrom)
AND (ISNULL(@TrnNoTo, '') = '' OR A21OPInvoiceHeader.TrnNo <= @TrnNoTo))
AND ((ISNULL(@RefNofrom, '') = '' OR A21GLTransactionHeader.DocNo >= @RefNofrom)
AND (ISNULL(@RefNoTo, '') = '' OR A21GLTransactionHeader.DocNo <= @RefNoTo))
AND ((ISNULL(@CustCodeFrom, '') = '' OR A21GLTransactionHeader.Code >= @CustCodeFrom) AND (ISNULL(@CustCodeTo, '') = '' OR A21GLTransactionHeader.Code <= @CustCodeTo)) 
)tblResult

group by  
[Transaction],Company, TrnType, TrnNo,Code, CName, DocNo, TrnScreen, TrnGrp, SCustomer,TrnDate, SalesPerson
END

**Comment by zeusa2000** [comment]
can view the report now and same report with clarity.

![image](https://user-images.githubusercontent.com/51438852/62529231-d91e4b80-b870-11e9-88b9-5d6d9729a7eb.png)
