### ISSUE TITLE
Finance -> Ledger -> Operations -> Enter GL Opening Balance (tab sequence)

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#18]
![2019-02-26_08h57_32](https://user-images.githubusercontent.com/47963293/53379267-e2db8300-39a3-11e9-85d0-bfdc8a3a8d80.png)

**Comment by ErwinMetra** [comment]
![2019-02-26_08h58_03](https://user-images.githubusercontent.com/47963293/53379297-04d50580-39a4-11e9-95a6-47c86427167b.png)

**Comment by ZawZawThein** [comment]
**Changeset 9923
Affected file:  Areas\GeneralLedger\Views\A21GLOpenItem\A21GLOpenItem_Script.cshtml**

**Comment by jessa21** [comment]
same with #64 
press ESC, ESC button , it won't go to Preview button...  
accept row - it won't open a new line detail

**Comment by ZawZawThein** [comment]
Changeset: 10175
Affected file:  Areas\GeneralLedger\Views\A21GLOpenItem\A21GLOpenItem_Script.cshtml

**Comment by zeusa2000** [comment]
Can do additional line and can preview the report also.

![image](https://user-images.githubusercontent.com/51438852/62911553-61dc4080-bdb7-11e9-8942-853e38582164.png)

![image](https://user-images.githubusercontent.com/51438852/62911583-73254d00-bdb7-11e9-8d37-2a9398deca28.png)
