### ISSUE TITLE
Sales=>Billings=>Report&Queries=>Document Printing=>Sales Quotation Report Under Construction.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#188]
Sales Quotation Report Under Construction.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/f9b5fb5d-fb1c-4996-8d3e-51ef74618224)

**Comment by ZawZawThein** [comment]
![111](https://user-images.githubusercontent.com/47886841/62459662-0225da00-b7a6-11e9-9d33-6a29219c8f24.png)

**Comment by ZawZawThein** [comment]
We can check these two table record exit or not.
select * from U21SelDoc where TrnType = 'CQ'
select * from U21SelDocUser where TrnType = 'CQ'

**Comment by zeusa2000** [comment]
Can view now the report.

![image](https://user-images.githubusercontent.com/51438852/62919042-108e7a00-bdd4-11e9-9edc-a1944468787e.png)
