### ISSUE TITLE
Finance -> Ledger -> Operations -> Enter GL Opening Balance (EDIT GO)

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#19]
![2019-02-26_08h59_02](https://user-images.githubusercontent.com/47963293/53379323-2209d400-39a4-11e9-95c2-8b501c741b78.png)

**Comment by ZawZawThein** [comment]
Changeset: 9847
Affected file: A21GLOpenItem_Script.cshtml

**Comment by jessa21** [comment]
@ZawZawThein 
Edit PDSU > Save > error 
http://a21.sg:94/GeneralLedger/A21GLOpenItem/30
![image](https://user-images.githubusercontent.com/47977411/56120018-d2a55480-5f9f-11e9-9f4f-8c16e6c3ef71.png)

**Comment by ZawZawThein** [comment]
Changeset 10134,10135

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/59183212-1bdbe400-8b9e-11e9-998c-bf3122298540.png)
![image](https://user-images.githubusercontent.com/51438852/59183379-68272400-8b9e-11e9-95b2-c778650b283b.png)
![image](https://user-images.githubusercontent.com/51438852/59183453-9d337680-8b9e-11e9-8e9d-5a9f3655fcc5.png)

As per testing we can now update the pdsu but the only problem is the spelling on the result box. should be PDSU not PUSU. See attached file for reference.

**Comment by ZawZawThein** [comment]
Changeset: 11374
Affected file: A21GLOpenItemController.cs

**Comment by zeusa2000** [comment]
As per testing PDSU is correct now and can save the transaction and view the report also.

![image](https://user-images.githubusercontent.com/51438852/62911374-c1861c00-bdb6-11e9-943c-26f9cdda44ab.png)

![image](https://user-images.githubusercontent.com/51438852/62911378-c3e87600-bdb6-11e9-99e0-ed02957984fc.png)

![image](https://user-images.githubusercontent.com/51438852/62911384-c6e36680-bdb6-11e9-9483-a4bd65b6367a.png)
