### ISSUE TITLE
Sales=>Billings=>Report&Queries=>Document Printing=>Delivery Order Direct Report Under Construction.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#190]
Delivery Order Direct Report Under Construction.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/e1c935ab-456b-45aa-b61a-1cf603e44c51)

**Comment by ZawZawThein** [comment]
Changeset **11520
Add rptCU.repx**
DataSet: CU.xsd

**Comment by zeusa2000** [comment]
Report same like clarity.

![image](https://user-images.githubusercontent.com/51438852/62920292-e50d8e80-bdd7-11e9-933e-d5cc5256c412.png)
