### ISSUE TITLE
 Font type script code display during PREVIEW

### ISSUE THREAD

**Issue by roxannebernabe** [a2000-erp-team/WEBERP#2]
NAVIGATION: Payables -> Reports & Queries -> Master Listing
![error](https://user-images.githubusercontent.com/47958190/53317647-714df700-3907-11e9-80f6-7f93c979ff63.png)

**Comment by ZawZawThein** [comment]
Fixed: Remove Param1 in design and before print event devexpress script 
Changeset 9784

**Comment by ZawZawThein** [comment]
New Changeset 9840
Affected file R21APReportsController.cs

**Comment by jessa21** [comment]
checked
