### ISSUE TITLE
Finance -> Ledger -> Operations -> Enter GL Opening Balance (Check is Warn Unbalance)

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#20]
![2019-02-26_09h00_22](https://user-images.githubusercontent.com/47963293/53379362-4fef1880-39a4-11e9-827e-b2c5e1d5f3fb.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9791

**Comment by ErwinMetra** [comment]
Now, there is a prompt message asking to Cancel or Ok to proceed.
