### ISSUE TITLE
Sales=>Billings=>Report&Queries=>Sales Analysis Report=>(NPC) Sales Analysis - Product - Customer Group Wise Report is blank.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#207]
(NPC) Sales Analysis - Product - Customer Group Wise Report is blank.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/b7b3c432-aab1-46eb-abbe-9c32cbc857c2)

**Comment by ZawZawThein** [comment]
add R21MISSalesNPCProductCustomerGroup.repx

**Comment by zeusa2000** [comment]
As per checking matched in the current weberp format report.


![image](https://user-images.githubusercontent.com/51438852/63243865-60ff4f00-c28e-11e9-8b6d-5b18bbf1ab3d.png)
