### ISSUE TITLE
Finance -> Ledger -> Operations -> Enter GL Opening Balance (PDSU check)

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#21]
![2019-02-26_09h01_24](https://user-images.githubusercontent.com/47963293/53379425-76ad4f00-39a4-11e9-832d-f8267a9ffd7c.png)

**Comment by ErwinMetra** [comment]
Not fully fixed yet.
Pls refer to GO 11.
Front end, shows that the line detail show no Project.
But in A21GLTransactionDetail, it shows Project NONE.

By right, when user clicks on SAVE button, the system should check if the header has PDSU as well as the Line details has PDSU as well.

**Comment by ZawZawThein** [comment]
Changeset **9989**

Run Script: 
update SMCProject set  Code='NONE' where Code='None'

**Comment by jessa21** [comment]
PDSU Checked.
