### ISSUE TITLE
Sales=>Billings=>Report&Queries=>Sales Analysis Report=>(NPC) Sales Analysis - Customer - Product Group Wise Report is Blank.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#210]
(NPC) Sales Analysis - Customer - Product Group Wise Report is Blank.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/fe8ccecd-eedf-4a02-bfa5-8497b02bd6b0)

**Comment by ZawZawThein** [comment]
add R21MISSalesNPCCustomerProductGroup.repx

**Comment by zeusa2000** [comment]
As per checking matched in the current weberp format report.

![image](https://user-images.githubusercontent.com/51438852/63243084-111f8880-c28c-11e9-9d97-391124456c35.png)
