### ISSUE TITLE
Sales=>Billings=>Report&Queries=>Sales Analysis Report=>(NPC) Sales Analysis - Customer Group Wise Report is blank.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#212]
(NPC) Sales Analysis - Customer Group Wise Report is blank.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/739873f9-1e12-440a-86a7-07736bb4381a)

**Comment by ZawZawThein** [comment]
add report 
R21MISSalesNPCCustomerGroup.repx

**Comment by zeusa2000** [comment]
As per checking matched in the current weberp format report.


![image](https://user-images.githubusercontent.com/51438852/63244125-221dc900-c28f-11e9-9e78-09fca2b31630.png)
