### ISSUE TITLE
Home -> System Manager -> Document Numbering Scheme

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#22]
![2019-02-26_09h21_54](https://user-images.githubusercontent.com/47963293/53380160-60ed5900-39a7-11e9-9bba-7d26e07ad643.png)

**Comment by ZawZawThein** [comment]
Changeset 9772

**Comment by ZawZawThein** [comment]
Changeset 9757
Changeset 9760

**Comment by ErwinMetra** [comment]
In windows ERP, this is the screen for **By Year Month**
![2019-03-01_10h27_00](https://user-images.githubusercontent.com/47963293/53612087-e6714300-3c0b-11e9-811b-93f8ab70d72b.png)

In the web ERP,  this is the screen for **By Year Month**
![2019-03-01_10h22_35](https://user-images.githubusercontent.com/47963293/53612103-f852e600-3c0b-11e9-8e7a-f9b5dc665d5a.png)

There is a difference.
Instead of **Number Limit**, it should be ***No. of Digits**

**Comment by ZawZawThein** [comment]
Changeset: 9810

**Comment by jessa21** [comment]
Done
