### ISSUE TITLE
Sales=>OrderProcessing=>Report Queries=>Sales Analysis Report=>Sales Analysis - Customer Wise(Separate Sales Return)

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#251]
Report cannot preview.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/cd57ae2d-7a88-4bd8-8c97-24efebedc304)

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/60780801-7141eb80-a172-11e9-9cc0-7d94103ab185.png)

**Comment by ZawZawThein** [comment]
Repx Name : R21MISCustomerSalesReturn.repx
DataSet: R21MISSalesReturn

**Comment by zeusa2000** [comment]
Can view now the report same like in the clarity.

![image](https://user-images.githubusercontent.com/51438852/62918953-d2915600-bdd3-11e9-9401-f2ec75c2787e.png)
