### ISSUE TITLE
Sales=>OrderProcessing=>Report Queries=>Sales Analysis Report=>Sales Analysis - Customer Territory Wise

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#253]
Report cannot preview.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/7be5ee35-b22b-45ae-9bd5-fc28e1311765)

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/60780905-df86ae00-a172-11e9-8bc9-65b731665a82.png)

**Comment by ZawZawThein** [comment]
Please check with Clarity.

**Comment by zeusa2000** [comment]
Paired in clarity.

![image](https://user-images.githubusercontent.com/51438852/62918252-b1c80100-bdd1-11e9-9fae-92574f504eb6.png)
