### ISSUE TITLE
Sales=>OrderProcessing=>Report Queries=>Sales Analysis Report=>Sales Analysis - Customer Location Wise

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#254]
Report cannot preview.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/017ddb53-9e42-447a-b31b-a4051403b1ff)

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/60780956-080ea800-a173-11e9-90b2-e60917e8500f.png)

**Comment by ZawZawThein** [comment]
![Screenshot 2019-07-29 11 02 37](https://user-images.githubusercontent.com/47886841/62022281-8a7a0d00-b1f1-11e9-8661-75040d86defd.png)

please try again. this report data can see.

**Comment by zeusa2000** [comment]
As per checking there is difference between clarity and weberp.

![image](https://user-images.githubusercontent.com/51438852/62108845-9ba04800-b2dd-11e9-8dba-398def654f2e.png)

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/85267322-b35d5d80-b4a7-11ea-8ba6-37e06c5c0202.png)
