### ISSUE TITLE
Sales=>OrderProcessing=>Report Queries=>Sales Analysis Report=>Sales Analysis - Customer Location Wise (Detailed)

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#255]
Report cannot preview.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/1e0adaf2-7b46-435e-8a62-7770171cc925)

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/60781009-40ae8180-a173-11e9-90e1-c2f0b56dbc06.png)

**Comment by ZawZawThein** [comment]
Changeset: 11392

**Comment by zeusa2000** [comment]
Can view now the report properly same with clarity.

![image](https://user-images.githubusercontent.com/51438852/62513167-9434ed80-b84d-11e9-8f78-14160852fc29.png)
