### ISSUE TITLE
Approval Section is BLANK even though the SO has been submitted for approval already.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#26]
**Procurement-> Billings-> Master Approval.**
![image](https://user-images.githubusercontent.com/47963355/53396711-1e943e00-39e0-11e9-82b2-77269e16e50e.png)

But when it goes to the transaction, the approval section shows blank even though it has been submitted already for approval.
![image](https://user-images.githubusercontent.com/47963355/53396812-6024e900-39e0-11e9-920a-dd1dacaf5b95.png)

Issue: This means the approver can proceed to approved or reject the transaction.

**Comment by ZawZawThein** [comment]
Changeset 9859

**Comment by jessa21** [comment]
view approver OK
