### ISSUE TITLE
Ledger-> Reports & Queries -> Master Listing - Chart of Account (Cash Flow) under Construction

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#27]
Master Listing - Chart of Account (Cash Flow) under Construction
![image](https://user-images.githubusercontent.com/47963355/53397056-0ffa5680-39e1-11e9-813c-31bdab480981.png)

**Comment by ZawZawThein** [comment]
Changeset 9860,9861,9862

**Comment by jessa21** [comment]
preview ok
