### ISSUE TITLE
Ledger-> Reports & Queries -> Master Listing-> Master Listing (PDSU). Use selected project screen is empty when open even though there are a lot of Projects

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#28]
Issue: Use selected project screen is empty when open even though there are a lot of Projects
![image](https://user-images.githubusercontent.com/47963355/53397779-f35f1e00-39e2-11e9-91ae-e3028d428043.png)

![image](https://user-images.githubusercontent.com/47963355/53397829-1ab5eb00-39e3-11e9-9476-496bfd473c4e.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9795

**Comment by jessa21** [comment]
Selected Project, Dept, Unit, Section OK to preview
