### ISSUE TITLE
Ledger-> Reports-> Transaction Listing -> sort by Date. No report generated

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#31]
![image](https://user-images.githubusercontent.com/47963355/53398065-afb8e400-39e3-11e9-9d6b-dc0fa12368d5.png)

**Comment by zawuniqesolutions** [comment]
Same with https://github.com/a2000-erp-team/WEBERP/issues/30

**Comment by jessa21** [comment]
ok Preview
