### ISSUE TITLE
Ledger-> Reports-> Transaction Listing  (with detailed narration) under Construction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#32]
![image](https://user-images.githubusercontent.com/47963355/53398144-de36bf00-39e3-11e9-83d2-701f854036ce.png)

**Comment by ZawZawThein** [comment]
Changeset: 9872
Affected file:   **R21GLTransactionDetailNarration.repx**

**Comment by jessa21** [comment]
OK
