### ISSUE TITLE
Inventory=>STKTransaction=>Report=>Reports&Queries=>Stock Valuation Report under construction.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#328]
Report under construction.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/6aacd661-0edc-49f9-bc0a-f90f14b5edae)

**Comment by ykauniqe** [comment]
It is working fine
![Capture](https://user-images.githubusercontent.com/47884745/61855257-c2c5d680-aee5-11e9-9e3a-32e929ceaeae.PNG)

**Comment by zeusa2000** [comment]
Done, same image with clarity report.

![image](https://user-images.githubusercontent.com/51438852/61924558-edbe3200-af9a-11e9-9ced-f65ccd7f0dac.png)
