### ISSUE TITLE
Inventory=>STKTransaction=>Report=>Reports&Queries=>Stock Valuation By Product Group,Brand,Model

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#329]
Report under construction.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/95742104-1521-4307-b161-a657583a5377)

**Comment by ykauniqe** [comment]
It is working fine
![Capture](https://user-images.githubusercontent.com/47884745/61855035-50ed8d00-aee5-11e9-8af3-1abee434495b.PNG)

**Comment by zeusa2000** [comment]
Done, Same image with clarity report.

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/61924480-93bd6c80-af9a-11e9-9288-b1f733d04dee.png)
