### ISSUE TITLE
Unnecessary string in the title bar: / th>

### ISSUE THREAD

**Issue by roxannebernabe** [a2000-erp-team/WEBERP#33]
PROCUREMENT->Purchase Operations-> U21CustomClearanceDashboard

![error](https://user-images.githubusercontent.com/47958190/53398797-7bdebe00-39e5-11e9-932c-14a9b66b57c4.png)

**Comment by ZawZawThein** [comment]
Changeset: 9816
Affected File: **Areas\Purchase\Views\U21CustomClearanceDashboard\U21CustomClearanceDashboard_Content.cshtml**

**Comment by jessa21** [comment]
Checked
