### ISSUE TITLE
Inventory=>STKTransaction=>Report=>Reports&Queries=>Stock Valuation (Landscape) Report under construction.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#330]
Report under construction.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/0742d643-e408-4ea5-8944-137decdda7ce)

**Comment by ykauniqe** [comment]
It is working fine
![Capture](https://user-images.githubusercontent.com/47884745/61854605-73cb7180-aee4-11e9-8fbf-7f38b02cf830.PNG)

**Comment by zeusa2000** [comment]
Done, Same figure with clarity report.
