### ISSUE TITLE
Inventory=>STKTransaction=>Report=>Reports&Queries=>Stock Valuation By Currency  Report under construction.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#331]
Report under construction.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/0453e804-5c8f-47af-8e96-c40d9177c2a2)

**Comment by ykauniqe** [comment]
It is working fine
![Capture](https://user-images.githubusercontent.com/47884745/61853416-dff8a600-aee1-11e9-9cbf-44100aaef90b.PNG)

**Comment by zeusa2000** [comment]
Done Same with Clarity output.
