### ISSUE TITLE
No Items reflect when clicking the selection drop down menu

### ISSUE THREAD

**Issue by roxannebernabe** [a2000-erp-team/WEBERP#34]
PROCUREMENT->Purchase->Purchase Requisition
![error](https://user-images.githubusercontent.com/47958190/53398893-b183a700-39e5-11e9-8f80-0e6795cf7757.png)

**Comment by zawuniqesolutions** [comment]
This is not bug. That is only not understanding Requirement Spec.
You need to setup.

1) ‘Tie to Salesperson’ for current Login User (under User Maintenance Page)
2) ‘Department’ for this Salesperson Tie (under Employee Maintenance Page)
3) ‘Department’ in the MSTProduct page (under Procurement > Admin > Item Master (Service) > Department tab)

**Comment by jessa21** [comment]
No product selection 
![image](https://user-images.githubusercontent.com/47977411/56118269-7c82e200-5f9c-11e9-8b25-c1b4e33c8761.png)

**Comment by zawuniqesolutions** [comment]
Please make required setup for this Dropdown as RQ said.
This is not bug, just need to setup by the following instruction.

1. Choose ‘Tie to Salesperson’ for current Login User (under User Maintenance Page)

2. Choose ‘Department’ for this Salesperson Tie (under Employee Maintenance Page)

3. Setup 'Department’ in the MSTProduct page (under Procurement > Admin > Item Master (Service) > Department tab)

**Comment by zeusa2000** [comment]
As per testing of 1 transaction all are working properly and saved. See attached image for reference.

![image](https://user-images.githubusercontent.com/51438852/59583342-990ed800-910d-11e9-8a25-4f9bda82630c.png)

![image](https://user-images.githubusercontent.com/51438852/59583392-b80d6a00-910d-11e9-88b1-e2fe2e192718.png)
