### ISSUE TITLE
Warehouse=>StkTransaction=>ReportQueries=>DocumentPrinting=>Stock Transfer

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#346]
Page under construction.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/e2f28a6b-4a9d-41e7-a015-cd6b83da7742)

**Comment by ZawZawThein** [comment]
Please test again. I already fix it.

**Comment by zeusa2000** [comment]
Can view now the report.

![image](https://user-images.githubusercontent.com/51438852/61932204-57e3d080-afb5-11e9-9265-3cbfcaccaed0.png)
