### ISSUE TITLE
Finance=>CashBook=>Report=>Reports&Queries=>Bank Reconciliation (Local Currency)

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#347]
Report need to enhance.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/8cbdeff5-fcb0-4241-8230-6e84d55462a9)

**Comment by Aungyetun991990** [comment]
![image](https://user-images.githubusercontent.com/47961353/62114761-50863500-b2dd-11e9-8cba-c4bb19df7917.png)
![image](https://user-images.githubusercontent.com/47961353/62114803-5ed45100-b2dd-11e9-9f16-3ee613cad34f.png)

**Comment by zeusa2000** [comment]
Paired same with clarity now.

![image](https://user-images.githubusercontent.com/51438852/62283278-cb895000-b483-11e9-8a7a-58cdd06b0f43.png)
