### ISSUE TITLE
Finance=>Cash Bank Book=>ReportQueries=>Reports&Queries=>Cash Bank Book (Local Currency)

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#348]
Page under construction.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/31ca1d80-56ab-4c1d-829f-7a39f1334e17)

**Comment by ykauniqe** [comment]
It is working fine
![Capture](https://user-images.githubusercontent.com/47884745/61844112-4bcc1600-aec4-11e9-9a15-37f33cd6cc74.PNG)

**Comment by zeusa2000** [comment]
As per clarity no amount should be displayed.

![image](https://user-images.githubusercontent.com/51438852/61924401-2e697b80-af9a-11e9-99f7-b19e91ecd312.png)

**Comment by zeusa2000** [comment]
As per checking matched in the current weberp format report.


![image](https://user-images.githubusercontent.com/51438852/63235087-bf1a3b00-c26a-11e9-9f62-fad69fcb8703.png)
