### ISSUE TITLE
Finance=>CashBook=>Report=>Reports&Queries=>Cash Bank Book (Foreign Currency)

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#349]
Page under construction.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/90360a90-019b-459f-b0e8-d09128d8d4cf)

**Comment by ykauniqe** [comment]
It is working fine.
![Capture](https://user-images.githubusercontent.com/47884745/61844002-f3951400-aec3-11e9-99cc-bdcfd06afe93.PNG)

**Comment by zeusa2000** [comment]
Done Same with the clarity file.
