### ISSUE TITLE
SALES - Order Processing - Operations - Customer Sales Order. Error when selecting line item in CO

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#366]
When selecting product on the line item, error below prompts:

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/77c619ac-8aaa-4578-b106-0d45ccbc016e)

**Comment by ZawZawThein** [comment]
Please try again, Is it already fixed.

**Comment by KatrinaCagaanan** [comment]
Resolved. :)
