### ISSUE TITLE
SALES - Order Processing - Operations - Customer Sales Order. Cannot save CO transaction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#367]
Trying to create a CO but cannot save the transaction. It prompts it successfully updated but "sales order listing" is empty and cannot retrieve the transaction.

**Comment by ZawZawThein** [comment]
Please try again.  I already fixed.
Changeset: 12557

**Comment by ykauniqe** [comment]
related issues https://github.com/a2000-erp-team/weberp/issues/366
