### ISSUE TITLE
Procurement - Product Acc Group 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#37]
http://a21.sg:94/Purchase/MSTProduct/230
Procurement > Admin >  Item Master > Full list of Product Acc Group did not appear  on the selection listing 

![image](https://user-images.githubusercontent.com/47977411/53398976-eabc1700-39e5-11e9-8bca-983991e3ab61.png)

**Comment by ZawZawThein** [comment]
Changeset 9787

**Comment by jessa21** [comment]
Checked.
