### ISSUE TITLE
Mandatory Cust PO still prompts even though user setting not set as manadatory Cust PO. (SALES - Order Processing - Operations - Customer Sales Order)

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#370]
Mandatory Cust PO still prompts even though user setting not set as mandatory Cust PO.
User id: Katrina (User maintenance -> Security-2 -> UNTICK Mandatory Customer's PO in Sales Order.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/63d38bd3-c5cb-4ad7-8868-6b49cb3da09a)

**Comment by ZawZawThein** [comment]
Changeset 12573
select MandatoryCustPONumber from MSTUser
