### ISSUE TITLE
Sales Order listing is blank.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#372]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/992e2e62-8a66-41fe-987b-39ad85a13b88)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/d4932c72-e2f1-4fcc-bbf2-0ada40418bab)

**Comment by ZawZawThein** [comment]
Changeset 12571 in DBscript
R21OPOrder Dataset- Changeset: 12570
Changeset 12572 : file: R21OPReportsController.cs

**Comment by ZawZawThein** [comment]
fix
: SELECT CountryCode FROM MSTSettings where ID=1
:  left JOIN MSTEmployee on MSTEmployee.Employee=A21OPOrderHeader.SalesPerson
