### ISSUE TITLE
Amount column in edit filter should be after GST amount. SALES - Order Processing - Operations - Customer Sales Order

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#374]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/ac219150-8fd7-428e-a597-f06ed5beaed8)

**Comment by ZawZawThein** [comment]
Affected file: 
Procedure: GetTransactionByWildCards_A21OPOrder ,
GetTransactionByWildCards_A21OPOrderWithoutFlag
