### ISSUE TITLE
Sales  Order Listing Pending (With PDSU) under construction - under SALES - Order Processing - Reports Queries - Reports&Queries

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#376]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/d46e9b35-be2f-4a36-b95b-aab438873bd7)

**Comment by ZawZawThein** [comment]
Affected file: R21OPReportsController
DataSet: R21OPOrderPDSL.repx
R21OPOrderPDSL.cs
R21OPOrderPDS.xsd
