### ISSUE TITLE
 All active GST types appear in the selection. Should follow the GST settings which GST types can be selected under SALES module. 

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#377]
CE Transaction:

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/7ef836e9-66d3-4d4f-b6dc-23d0532c47bb)

**Comment by ZawZawThein** [comment]
Changeset: 12617
