### ISSUE TITLE
Cloned CO228 to CO232 does not have GST amount.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#378]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/ae919618-adc6-4e9f-ac39-1415c83dfccb)

Additionally, when I open the CO 232, the GST selection is still there but no GST amt.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/d8b362af-1eea-4d09-b84e-013397dbcd02)

**Comment by ZawZawThein** [comment]
changeset: 12625
