### ISSUE TITLE
Don't Save to XLS the preview report

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#38]
Scenario 2: Preview Report in XLS
Creation of GP Transaction
Select Bank
-Select PDSU
-Select Currency
-Key-IN Payee
-Cheque No.
Add Details
-Select Account
-Key-in Amount (Debit or Credit)
-Then click Preview , then save to XLS (Nothing Happen)

Result : NOT CORRECT
![image](https://user-images.githubusercontent.com/47963668/53399291-abda9100-39e6-11e9-8a87-f0ab5c213e7f.png)

**Comment by ZawZawThein** [comment]
**Changeset 9868,9869,9870**
![export excel](https://user-images.githubusercontent.com/47886841/53943356-4e7fc780-40eb-11e9-8e08-e21414dc5eb0.png)

### Please test again. It can export to excel. Check Miscrosoft Excel program exit or not in PC. If doesn't have, please install office program.

**Comment by jessa21** [comment]
OK
