### ISSUE TITLE
Product Account Group - Sales account always becomes blank and other fields changes the mapping as well.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#381]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/38ebef04-93fe-4bef-bd22-4713bf77f987)

**Comment by ZawZawThein** [comment]
Changeset: 12631
Affected file: Areas\Purchase\Views\SMAccountGroupProduct\SMAccountGroupProduct_Script.cshtml
