### ISSUE TITLE
Load CO236 to CE105 (GST Inclusive/Exclusive - The GST was not captured when the CO was loaded to CE.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#383]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/1bfec7f2-71e9-4582-8732-2348d2921951)

**Comment by ZawZawThein** [comment]
Changeset: 12653
And 
Affectedfile: SQL\A21OPInvoiceonOrder\A21OPInvoiceonOrder_GetTransDetail.sql

**Comment by ZawZawThein** [comment]
Changeset 12685
