### ISSUE TITLE
Sales Analysis - Customer Wise report - wrong profit ratio

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#388]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/305a4055-2f95-4442-ac5b-8b7a333c6a2f)

**Comment by ZawZawThein** [comment]
Affected file: 
fuction: GetMISProfit
Procedure: MISSalesCustomer
Report: R21MISSalesCustomer.cs

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein , kindly recheck. Still wrong.

![image](https://user-images.githubusercontent.com/47963355/67444773-080cb800-f63d-11e9-9081-48234158ce96.png)

**Comment by ZawZawThein** [comment]
Write script in DEV report R21MISSalesCustomer.cs file

**Comment by KatrinaCagaanan** [comment]
resolved.
