### ISSUE TITLE
Sales Analysis Report - Salesperson wise issues

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#389]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/f349268e-1416-44e3-ad7a-7ac00316c0dd)

Should be format:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/e32e44be-bf1b-467c-98a2-127826571787)

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein , will re-open this due to a few things, pls see below:
![image](https://user-images.githubusercontent.com/47963355/67447059-40b08f80-f645-11e9-91ee-f9840b97fdc5.png)

**Comment by ZawZawThein** [comment]
Report: R21MISSalesPersonSummary.repx

**Comment by KatrinaCagaanan** [comment]
Resolved.
