### ISSUE TITLE
Procurement - Duplicated Purchase Order Type

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#39]
http://a21.sg:94/Purchase/SUPurchaseOrderType/400
![image](https://user-images.githubusercontent.com/47977411/53399668-64a0d000-39e7-11e9-975e-332b4c0177b0.png)

@ZawZawThein   Remove duplicate row query

delete U21Menus where ControllersName = 'SUPurchaseOrderType' and ItemNumber = 401

**Comment by ZawZawThein** [comment]
### IF EXISTS ( Select 1 from u21menus where ItemName='SUPurchaseOrderType' and ControllersName='SUPurchaseOrderType' and ItemNumber=401 and MenuCategory=5 )
	BEGIN
	     delete u21menus where ItemName='SUPurchaseOrderType' and ControllersName='SUPurchaseOrderType' and ItemNumber=401 and MenuCategory=5
	END
Go

**Comment by ZawZawThein** [comment]
Changeset: 9796

**Comment by jessa21** [comment]
Checked.
