### ISSUE TITLE
Sales Order Listing (Pending with PDSU) - CO Transactions already invoiced still appear in the report

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#390]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b2c47495-6136-471f-b624-5bb0e377fe3f)

**Comment by ZawZawThein** [comment]
Affected file: 
add procedure: [R21OPOrderOutstandingPDS]
repx file: R21OPOrderPDSL.repx
