### ISSUE TITLE
Sales Order Listing (With Invoice X ref) - Report is blank even though there are CO that are invoiced already

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#391]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/4eb7b9d2-85bf-488d-8cd6-4b90b4206a9b)

**Comment by ZawZawThein** [comment]
Changeset: 12750
Affected file: R21OPInvoiceOnDoOrderOrder.repx
Areas\Sales\Views\A21OPOrder\Script.cshtml
