### ISSUE TITLE
Sales Order Listing (Closed Order) - transactions not Closed appear in the report

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#392]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/82085def-4780-468d-a27a-bb91a8663c6e)

**Comment by ZawZawThein** [comment]
Changeset: 12738
Affected file: Areas\Sales\Views\A21OPOrder\Script.cshtml

**Comment by ZawZawThein** [comment]
select Remarks from A21OPOrderHeader where trnno = 252
if the remarks is not null, the order status is close.
