### ISSUE TITLE
Qty is being add up whenever the invoice qty is being edited (Issue for both CE & SE)

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#393]
Note: The qty can be corrected if I run the stock recal but system still keeps adding up the qty when I edit the qty.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a693449f-2698-4aec-90b0-5020d84c8e85)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 12835**
