### ISSUE TITLE
Stock Ledger format issues

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#394]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b13646ca-6d20-4996-ba53-048649f94958)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 12744** 

PS. For No. 2, you need to define how many Decimal Place you want to use in System Default setting.
![image](https://user-images.githubusercontent.com/47886892/66902722-206e4880-f027-11e9-9df0-159eeabfa908.png)

**Comment by KatrinaCagaanan** [comment]
Hi Zaw, everything is ok except that the report name becomes stock ledger with Fifo Detail. This should be the normal Stock ledger

![image](https://user-images.githubusercontent.com/47963355/66993541-516d7c80-f0fe-11e9-9ce4-b1b474708cbc.png)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 12837**
