### ISSUE TITLE
SE - additional transaction detail is empty

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#395]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b03df81c-aa8c-493c-a09d-0275ba8c939b)

**Comment by zawuniqesolutions** [comment]
Hi @KatrinaCagaanan 
Please attach video file when and how was happened for this issue.

**Comment by KatrinaCagaanan** [comment]
Hi @zawuniqesolutions , I checked this issue again and seems ok already. Will close now.

![image](https://user-images.githubusercontent.com/47963355/67067327-82a28700-f1a8-11e9-9ba8-fad3cf3739a0.png)
