### ISSUE TITLE
Purchase Order Listing (Pending) - Partial Invoiced: Purchase Order Listing (PENDING) still shows full amt of SO, even though I partially invoiced half of the order. By right, pending should be only S$50

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#398]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/9caf35f2-590f-4c74-a583-8e8fcb118a3a)

**Comment by zawuniqesolutions** [comment]
Need to publish.

**Changeset 12737**

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 12848**

**Comment by KatrinaCagaanan** [comment]
Not resolved yet. Tested and still the same. Will re-open.
![image](https://user-images.githubusercontent.com/47963355/67353101-4db97a00-f584-11e9-881f-c622a08802cf.png)

**Comment by KatrinaCagaanan** [comment]
Resolved.
![image](https://user-images.githubusercontent.com/47963355/67455093-0a800980-f65f-11e9-8bb1-a931c9416b94.png)
