### ISSUE TITLE
Supplier Invoice Listing - Subtotal shows 0 when the invoice has an amount.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#399]
Please refer to below:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/8cc6c87e-3f0f-454a-b71b-c03410b5846e)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 12739**
