### ISSUE TITLE
Reports & Queries shows duplicate tab Entries

### ISSUE THREAD

**Issue by roxannebernabe** [a2000-erp-team/WEBERP#4]
NAVIGATION: FINANCE-> Cash book-> REPORTS
![error](https://user-images.githubusercontent.com/47958190/53317911-6e073b00-3908-11e9-8831-8682fc53edcd.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9762

**Comment by jessa21** [comment]
Updated
