### ISSUE TITLE
Can't save new GST maintenance  

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#40]
![image](https://user-images.githubusercontent.com/47977411/53401327-936c7580-39ea-11e9-8820-cfecb7d4be42.png)

**Comment by ZawZawThein** [comment]
Go Page: Finance >Maintenance > GST type
Link:  http://a21.sg:94/GeneralLedger/SMGSTType/130

**Comment by ZawZawThein** [comment]
Changeset: 9849
Affected file: Areas\GeneralLedger\Views\SMGSTType\Content.cshtml
Areas\GeneralLedger\Views\SMGSTType\Script.cshtml

**Comment by jessa21** [comment]
@ZawZawThein 
![image](https://user-images.githubusercontent.com/47977411/55786810-8bbee700-5ae7-11e9-8a69-11dc2b2c278c.png)

**Comment by ykauniqe** [comment]
Nearly finished (root cause is Tax Rate %)

**Comment by ZawZawThein** [comment]
Changeset **10174**
Affected file: SMGSTTypeController.cs

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/59186918-b3453500-8ba6-11e9-9d52-9a5faf9b650f.png)

As per testing the creation of new GST is successfull. Attached is the screenshot of the transaction.

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/59187329-d02e3800-8ba7-11e9-8cac-1c28183eebab.png)

Will close the ticket now.
