### ISSUE TITLE
Procurement-Purchase-Operations-Purchase Order. Issue: Able to delete line item in SO even though has been invoiced already.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#400]
Procedure:

1. Create new SO transaction, for example 10 pcs
2. Load the SO to SE transaction (either partially or all items). 
3. Go back to SO transaction and edit/change the quantity in the line item from 10 qty to 12 qty
4. Accept Row.
5.  Delete the line item in the SO.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/30bef99b-430e-46ed-a5ab-fb7f0a1d1e13)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 12748**
