### ISSUE TITLE
SALES-Order Processing-Customer Sales Order. System allows to change CO qty lower than CE invoiced qty.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#401]
Scenario:
1. Create CO with 10 qty.
2. Click create CE button to create a CE (means invoiced the 10 qty).
3. Go back to CO transaction and edit the qty to 5 qty. System allows.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/2bca6019-c5f7-4c7f-97ff-03727d6c6eb2)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/46f2043b-d06d-4ed1-8f14-ee6b89cdded3)

**Comment by ykauniqe** [comment]
related ticket https://github.com/a2000-erp-team/WEBERP/issues/402

**Comment by ZawZawThein** [comment]
Changeset: 12766
