### ISSUE TITLE
PROCUREMENT - Purchase - Purchase Order. System allows to change SO qty lower than SE invoiced qty

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#402]
Scenario:
1. Create SO with 10 qty.
2. Create a SE transaction and load the SO to SE (means invoiced the 10 qty).
Go back to SO transaction and edit the qty to 5 qty. System allows.

![image](https://user-images.githubusercontent.com/47963355/66983402-1746af80-f0eb-11e9-94fd-8e3748a4b824.png)

![image](https://user-images.githubusercontent.com/47963355/66983559-6260c280-f0eb-11e9-8a21-44cbc423f604.png)

**Comment by ykauniqe** [comment]
related ticket https://github.com/a2000-erp-team/WEBERP/issues/401

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 12783** 

PS. Please test with another new SO and SE for this procedure. Do not use existing one beacause of that one is already wrong.
