### ISSUE TITLE
PROCUREMENT-Purchase-Purchase Order-Additional Transaction detail. Value field in Additional Transaction is wrong. (Check also for SE) 

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#403]
Kindly do for SO and SE.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/e0e7a43b-28cf-4a3f-b400-09e9baba104c)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 12807**
