### ISSUE TITLE
PROCUREMENT-Order Processing-Supplier Bills-Invoice on PO-Additional Transaction Detail. GST amount showing  wrong.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#404]
Scenario:
-Enter line item in SE, 10 qty @ S$10 with 7% GST exclusive. Hence, GST is S$7.00 (S$100*7%). But GST on additional line item shows 700.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/1e7f1abb-5061-427b-8edd-3b1816ea8e89)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 12807**
