### ISSUE TITLE
SALES-Order Processing-Invoice on Order. Cannot load Lot id in CE.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#405]
There's an error message when trying to load the line in the CE.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/6ba76ab8-31a9-4a84-89f5-345314222fd8)

**Comment by ZawZawThein** [comment]
Changeset 12829
