### ISSUE TITLE
SALES-Order Processing-Invoice on Order. Created an item with FIFO costing but the cost is not being captured in the CE. When I create the CE, the CE does not have a cost.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#406]
Scenario:
-Created an item with FIFO costing
-Create a Purchase Invoice @ 10 unit price.
-Create a sales invoice but the cost captured was 0. by right it should be S$10 following the FIFO costing method.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/50e7d749-374c-4624-ab29-49b61320c795)

**Comment by ykauniqe** [comment]
Changeset 12899
Changeset 12900 for FIFO costing in update stock

**Comment by KatrinaCagaanan** [comment]
Resolved.
