### ISSUE TITLE
PROCUREMENT-Order Processing-Supplier Bills-Invoice on PO. Wrong GL Posting for SE with LANDED COST for CLOSING STOCK POSTING

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#407]
Stock Posting Method: Closing Stock Posting
Scenario: SE with Landed Cost of 100
-Created SE transaction with S$100 Landed Cost
Issue: Wrong Posting if with LANDED COST

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/1d78bea9-d30e-43c8-b93b-fbd482e920cd)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 12945**

**Comment by KatrinaCagaanan** [comment]
Resolve
