### ISSUE TITLE
SALES (CE), Purchase (SE) - Delete CE120 and SE106 but still appears in Stock ledger

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#408]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/4d3b80eb-c334-4e73-bde4-2b233be33ecc)

**Comment by ZawZawThein** [comment]
Please test again with new product, new customer and new order and invoice.

**Comment by KatrinaCagaanan** [comment]
Resolve
