### ISSUE TITLE
SALES-Reports Queries-Reports & Queries- Sales Analysis-Customer Wise (tick detailed report). Report format issues

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#409]
Sales Analysis-Customer Wise - Detailed report issues
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/4fd90429-3d67-4d25-86f7-889dff4045f5)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b54a4be9-96ea-434e-86d1-bdc48da9181e)

**Comment by ZawZawThein** [comment]
repx file: R21MISSalesCustomerDetail.repx
procedure: R21MISSalesCustomerDetail

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein , I checked the report now and its under construction.
![image](https://user-images.githubusercontent.com/47963355/67836570-f5581e80-fb27-11e9-9c5d-2710277b9e48.png)

**Comment by KatrinaCagaanan** [comment]
Still the same. The report  is under construction. Kindly note this is "detailed report".
![image](https://user-images.githubusercontent.com/47963355/67996747-c064dc80-fc8b-11e9-8cdf-4cd8d22a4d4b.png)

**Comment by ZawZawThein** [comment]
Affected procedure : R21MISSalesCustomerDetail

**Comment by KatrinaCagaanan** [comment]
Resolved. Thanks
