### ISSUE TITLE
PROCUREMENT-Reports Queries-Reports & Queries- Supplier Invoice Listing. Supplier Invoice Listing shows a few invoices only., does not shows invoices from 10 Oct onwards.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#412]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/f4ee5194-cafe-466a-85d8-abe293d6e2a6)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/c9220f92-b14b-49f1-8f41-23d8c9ce5348)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 12907**

**Comment by KatrinaCagaanan** [comment]
Resolved
