### ISSUE TITLE
SALES-Order Processing-Cash Invoice. Error prompts to enter bank code even though bank code has been entered

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#413]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/c00e91b2-cd63-463f-9c2d-506176ae54e4)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/d80cfb7a-2855-4ebf-a198-ea90282fdd15)

**Comment by ZawZawThein** [comment]
Changeset: 13008

**Comment by KatrinaCagaanan** [comment]
Resolved
