### ISSUE TITLE
SALES-Order Processing-Credit Invoice & Cash Invoice. Deleted CR437 & CA67 but still appears in Stock ledger

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#414]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/bcef1fec-1d79-4c45-977f-fb488d3a334a)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/92dc08b1-c5bd-40d8-b8e6-4e8529099981)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a6bc8231-fbfc-4b36-8600-690ae8b48960)

**Comment by ZawZawThein** [comment]
Changeset: 13012

**Comment by KatrinaCagaanan** [comment]
Resolved
