### ISSUE TITLE
SALES - Order Processing - Invoice on Order(CE) and Credit Invoice (CR). System still allows negative stock even though setting is "Do Not Allow Negative Stock" from System Settings

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#415]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/4e3abe27-0a4e-4770-9710-e5db309e4718)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/fa1273dd-0466-48b1-a486-fe56e14fbdd7)

**Comment by ZawZawThein** [comment]
check__A21Setting.NegativeStockCheck(isCEAutoCheck) 
Changeset: 13010
Affected file: Common\PostingTransaction.cs 
**UpdateStock Function

**Comment by KatrinaCagaanan** [comment]
Resolved
