### ISSUE TITLE
SALES-Order Processing- Credit Invoice (CR). Deleted line details but still appears in Stock ledger.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#416]
Kindly rectify for all succeeding Sales Transaction types as well - CA, CM.CD,CC,CU,CY

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/ab4a7e6a-17ed-4e65-982a-428956ce21cc)

**Comment by ZawZawThein** [comment]
Related ticket 414

**Comment by KatrinaCagaanan** [comment]
Resolved
