### ISSUE TITLE
SALES -Order Processing - Credit Invoice (CR). GST posting not posted resulting to unbalanced GL transaction for both GST incl and GST Excl.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#417]
Settings: Cost of Sales Posting

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/8008cc56-8443-4f35-be0e-6700cf9ef55e)

**Comment by ykauniqe** [comment]
changeset 13163

**Comment by KatrinaCagaanan** [comment]
Resolved
