### ISSUE TITLE
SALES-Order Processing- Credit Invoice. Cloned CR does not reflect in Customer Invoice Listing, GL Transaction Listing and stock ledger

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#418]
Scenario: 
-Go to CR442. 
-Click clone button. Transaction cloned to CR449.
-Check related reports customer invoice listing, Stock ledger and GL transaction listing but the transaction CR449 was not captured.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/219ec608-b9f8-432b-96c8-d92ce84a6af2)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a0c729b0-28ea-44af-942e-40301cad4411)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/c5a1a164-0512-4793-8d34-91794009d03e)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b2bd2c6e-2487-4b80-ba27-ac76ba1e8556)

**Comment by ZawZawThein** [comment]
Fix save date only in A21GLTransactionHeader
(GLH.TrnDate = DateTime.Now.Date) 
Affected file: A21OPInvoiceCreditController.cs

**Comment by KatrinaCagaanan** [comment]
Resolved
