### ISSUE TITLE
SALES-Order Processing-Credit Invoice (CR). System allows to click confirm multiple times, creating multiple cloned CR. Kindly add validation when the transaction has been successfully cloned and close the the "transaction clone" window.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#419]
Scenario:
Cloned CR448 but click confirm button multiple times.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a7a9fac1-ba01-444a-8f7d-f7cabd84ef65)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/65e53175-3745-44bd-aaf0-aeab6bb8f292)

**Comment by ZawZawThein** [comment]
Changeset: 13022

**Comment by KatrinaCagaanan** [comment]
resolved
