### ISSUE TITLE
Ledger - Can't add Account Classification  (add button not available) 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#42]
http://a21.sg:94/GeneralLedger/SUGLClassLevel1/140#
Finance > Ledger > Maintenance > Account Analysis > No add button / no record level to select 
![image](https://user-images.githubusercontent.com/47977411/53405833-ac2d5900-39f3-11e9-80c1-ac0965d2a80f.png)

You may refer to Account Analysis in Clarity 
![image](https://user-images.githubusercontent.com/47977411/53406436-e814ee00-39f4-11e9-9207-454dc11b1220.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9893 
Changeset 9938

**Comment by jessa21** [comment]
done
