### ISSUE TITLE
Procurement-Order Processing- Supplier Bills- Credit Invoice (SI). The system prompts "insufficient stock" for SI and cannot proceed to save transaction. There shouldn't be a checking of negative stock balance because this is a stock receipt not issuance.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#420]
Scenario:
-Stock item Testproduct has negative qty.
-Create a SI transaction to received goods to cover the negative stock.
-System still prompts insufficient stock even though we are receiving stock and not issuing stocks.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/d63df913-f010-40d4-b15d-8f22a61de533)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13016**

**Comment by KatrinaCagaanan** [comment]
Resolved
