### ISSUE TITLE
Procurement-Order Processing- Supplier Bills- Credit Invoice (SI). Product Details window empty.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#421]
Scenario:
-Create SI Transaction.
-Edit the line item.
-Click the Product button to go to product and service maintenance, but window is empty.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a5e7bb07-4054-4574-9485-52a4c443e80f)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/de017e71-b72d-47df-85c2-f2697d14944a)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13016**

**Comment by KatrinaCagaanan** [comment]
resolved
