### ISSUE TITLE
Procurement-Reports Queries-Reports$Queries-Supplier Invoice Listing. Supplier Invoice Listing does not show SI transactions created. Please do for Supplier Listing (detailed report) too. Kindly check for SA (cash Invoice) as well.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#423]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/202e811b-e6fd-46b7-978a-463f81070044)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/c82c511b-1eb7-495e-bdc1-8c64f621a50f)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13018**

**Comment by KatrinaCagaanan** [comment]
Resolved
