### ISSUE TITLE
Procurement-Order Processing-GRN On Order. Unit price for reports Stock Ledger, Stock Transaction Listing and GL Transaction listing changes after deleting and re-entering the line item in SG transaction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#424]
Scenario:
-Created SO transaction with 1 line item 1 Qty @ S$10 total at S$10.
-Load the SO to the SG. All reports ok - Stock ledger, Stock transaction listing and GL Transaction.
-Go back to SG transaction and delete the line item then re-enter the line item. The unit price/cost showing in the stock ledger, stock ledger shows S$11 already. GL Transaction listing shows now at S$11, should be S$10.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/d7533e5d-7710-47f8-a6a5-e108a97089ab)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/84d789b1-9025-4562-a89c-9d84b45d133b)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/31d44ca1-19d2-4cad-a789-7b3e3aa5537b)

**Comment by zawuniqesolutions** [comment]
Waiting for publish
**Changeset 13274**

**Comment by KatrinaCagaanan** [comment]
Resolved
