### ISSUE TITLE
Procurement-Order Processing-Invoice on GRN. GST not captured on SP even though SO has 7% standard GST.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#425]
Scenario:
-Created SO with 7% standard GST
-Load SO to SG then to SP.
-But when load to SP, SP transaction do not have GST.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/f429ef5e-e7b0-453b-85b6-fc7eb1a0b1ea)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b86f06cf-a052-4268-ad0d-1d994096ded1)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/5586752d-89d9-4897-8726-2d21c8eed4e3)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/4efcc25e-a98f-4038-96af-29536467c4c9)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.
**Changeset 13263**

Hello @KatrinaCagaanan ,
There is new logic for getting GST by @jameslee888sg .
Please see the attached file for your testing process.
If there is any issue, please let me know.

[SaleTestCase.docx](https://github.com/a2000-erp-team/WEBERP/files/3878040/SaleTestCase.docx)

**Comment by KatrinaCagaanan** [comment]
Thanks for the info @zawuniqesolutions. :) Will take note during testing. Thanks

**Comment by KatrinaCagaanan** [comment]
Resolved
