### ISSUE TITLE
Procurement-Order Processing-GRN on Order. System still allows to delete GRN line item that has been invoiced already. Please also do for SN.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#426]
Scenario
-Create SO-SG-SP.
-Go back to SG and delete the line item that has already been invoiced to SP. System still allows.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/53d18d37-15c6-4d8d-b933-3bbfbd84d5cc)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/0f427a9f-a1e6-4ab9-b27f-cf600b39a62f)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.
**Changeset 13275**

**Comment by KatrinaCagaanan** [comment]
Tested in SG, ok.
Not yet tested in SN. Cannot create new transaction in SN.

**Comment by KatrinaCagaanan** [comment]
resolved
