### ISSUE TITLE
Procurement-Order Processing-Invoice on GRN. Cannot change the GST in SP.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#427]
Scenario:
-Created SN and load to SP.
-Tried to changethe GST inSP but cannot change.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b0f19f67-bd03-4647-b3fe-6c39d02572f7)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.
**Changeset 13266**

**Comment by KatrinaCagaanan** [comment]
Resolved
