### ISSUE TITLE
Procurement- Order Processing- SE/SI/SM/SA with GST Inclusive. Wrong cost in Stock ledger and Stock Transaction listing bec it includes the GST. By right cost should be without GST.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#428]
Scenario:
-Created an invoice with GST inclusive. Cost of item should not include the GST. But Stock ledger and stock transaction listing cost includes GST. For Example, S$90 inclusive of GST. Only the net amount of 84.11 should be the cost.
Note: GL Posting is correct. 
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/2977c194-941e-4bc8-9eb2-cfe22ab23240)

Stock Ledger wrong and Stock transaction listing - cost shows including GST
Correct total cost is 84.11
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/dd5c84b5-e9ce-4658-a6c7-a9951e3d99c7)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/18f00019-0f83-4926-af2e-4bd79289908d)

Below is correct GL Transaction listing
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/8e7ee0b0-8a93-4a4a-a448-820c80256c85)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13285**

**Comment by KatrinaCagaanan** [comment]
I tested and they are still not the same:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a0f9a667-b049-44d4-9a1c-a304e1c50848)

**Comment by KatrinaCagaanan** [comment]
Resolved
