### ISSUE TITLE
SALES-Order Processing-Operations-Credit Invoice with Deposit (CM). Wrong posting. Stock A/c and Cost of sales not posted.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#429]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/11b4f76c-526b-4c3d-9885-8964fd6c8cda)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/fb41b450-0046-449e-aa5b-d3d7a264ca68)

**Comment by ZawZawThein** [comment]
Changeset: 13280

**Comment by KatrinaCagaanan** [comment]
Resolved

**Comment by ykauniqe** [comment]
related ticket #474
