### ISSUE TITLE
Ledger - Validation Message "Duplicated Data" 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#43]
http://a21.sg:94/GeneralLedger/SUGLReportLevel1/150
1:  Level 1 
Final Account Layout > select Custom 2 format to create new final acc layout > add level 1 = 100 > system does not allow to add same level 1 "100" as Custom 1. it should allow to use same level 1 in different custom format. 
![image](https://user-images.githubusercontent.com/47977411/53406774-9f116980-39f5-11e9-9ce9-bb77ad651609.png)

2: Level 3
Level 3 > add 010 > duplicated data occurs.  System should allow to process . 
![image](https://user-images.githubusercontent.com/47977411/53407384-0da2f700-39f7-11e9-81ac-4e4d9cffd959.png)

**Comment by ZawZawThein** [comment]
Changeset 9803

**Comment by jessa21** [comment]
when add Level 3 > system prompt msg

![image](https://user-images.githubusercontent.com/47977411/53785099-522c1680-3f52-11e9-99dc-19173d48a857.png)

ZZT Comment: Please should be accept row after insert data and then can save row.

**Comment by jessa21** [comment]
@ZawZawThein  - When I click SAVE , system prompt error msg . data not saved. 

http://a21.sg:94/Receivables/MSTCustomer/80

![image](https://user-images.githubusercontent.com/47977411/53932597-4ddc3680-40d5-11e9-8e21-1aa69208a8c9.png)

**Comment by ZawZawThein** [comment]
fix [FK_SMAccountGroupSupplier_SMAccountGroupSupplier] error 
**Changeset 9904
Affected file:  \SQL\MSTCustomer\MSTCustomer_SaveData.sql**

**Comment by jessa21** [comment]
done
