### ISSUE TITLE
SALES-Order processing-Operations-Credit Invoice with Deposit (CM). CM does not appear in Customer Invoice Listing report. Please check for all customer invoice listing reports.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#430]
Scenario:
Created CM7 but transaction does not appear in customer invoice listing report.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/cec851e5-70e4-4f10-9ea9-7520616ddfa5)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/1582edc8-ee49-4fbc-b7d4-59672482da5e)

**Comment by ZawZawThein** [comment]
Changeset: 13265

oph.DOType = "CM";
oph.DONo = Convert.ToInt32(m.TrnNo);

**Comment by KatrinaCagaanan** [comment]
Resolved
