### ISSUE TITLE
Procurement-Order Processing-Credit Invoice with Deposit (SM). SM transaction does not appear in GST reports.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#432]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/342f430b-4d01-4954-88f5-1e8d8e24bbe0)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/9ab05a54-c5fe-4316-afa0-36ad7367accf)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13281**

**Comment by KatrinaCagaanan** [comment]
Resolved
