### ISSUE TITLE
Sales-Order Processing- Credit Invoice with deposit (CM). Deleted line item in CM still appears in stock ledger.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#434]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/ea6bc510-12d8-4fa6-8d22-44c76e046a5c)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/383b6183-5a10-42eb-bf23-da294ac5a3e7)

**Comment by ZawZawThein** [comment]
Please try again.

**Comment by KatrinaCagaanan** [comment]
Resolved
