### ISSUE TITLE
Sales-Order Processing-Cash Invoice (CA). Cannot search item in CA transaction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#435]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/71c9b1e2-d3c8-4783-8e37-e7d9c76923bc)

**Comment by ZawZawThein** [comment]
Changeset: 13271

**Comment by KatrinaCagaanan** [comment]
Resolved
