### ISSUE TITLE
COA Mapping not appeared in Master COA Listing 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#44]
Once we mapped the COA, we can view the Rep Lev 1 in format 2 

http://a21.sg:94/GeneralLedger/MSTChartAccount/120
![image](https://user-images.githubusercontent.com/47977411/53409328-a2a7ef00-39fb-11e9-96a3-636e490019ec.png)

http://a21.sg:94/GeneralLedger/R21GLReports/90
![image](https://user-images.githubusercontent.com/47977411/53409007-e6e6bf80-39fa-11e9-9af7-627ce45a3ff6.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9815
Changeset 9817

**Comment by jessa21** [comment]
Checked.
