### ISSUE TITLE
Procurement-Order Processing-GRN DIRECT (SN). Cannot proceed to enter line item. With Error message

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#440]
Tried to create GRN Direct but when I click accept row, error message prompts.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/98fcbeaa-d4a9-48d6-9a35-86d9283ded98)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13353**

**PS.** I already fixed other operations for that logic.

**Comment by KatrinaCagaanan** [comment]
Resolved
