### ISSUE TITLE
SALES-Order Processing- CE,CR,CA,CM does not appear in GST Grouping Listing by (GST type)

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#443]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/c8209fd0-6ce5-4420-8784-1aa8ec688930)

These transactions should appear.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/347caa1d-9fbf-458c-8920-170cba854d9b)

**Comment by ZawZawThein** [comment]
GST Grouping Detail Listing ( By GST Type) will be fine after run db script.
Using Dataset: **GSTGroupDetailListingDataset**

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein,

Will reopen this ticket:
1. Pls remove CY in the GST reports. Only invoice should show.
2. Kindly have the amounts in 2 decimal places.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/5d911dba-8153-4c15-9f45-1ed1bceafb1d)

**Comment by KatrinaCagaanan** [comment]
Hi @ykauniqe ,

I will re-open this ticket. The subtotals and grandtotal should be in 2 decimal places.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b5cf4597-7992-487a-8a90-a4bad6dfed56)

**Comment by KatrinaCagaanan** [comment]
Resolved
