### ISSUE TITLE
SALES-Order Processing- CE,CR,CA,CM does not appear in GST Grouping Listing (ALL)

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#445]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/3f61ef17-73ed-4316-bd1a-e30263566dbe)

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein,

The invoice appear already but with a few more things:
1. CY should not appear in the GST reports, only invoices.
2. Subtotals are wrong
3. The payclain column should be in 2 decimal places. Kindly check for all columns and amts - should be 2 decimal places.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/ad7da4fb-1708-4450-b514-2a15fc549144)

**Comment by ZawZawThein** [comment]
Changeset 13372
Changeset: 13373( DBScript)

**Comment by ykauniqe** [comment]
related ticket 443

**Comment by ykauniqe** [comment]
related ticket #433

**Comment by KatrinaCagaanan** [comment]
Resolved
