### ISSUE TITLE
Error : Can't save Project 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#45]
http://a21.sg:94/GeneralLedger/SMCProject/170
Ledger > Mainteanance > Project > Create new project > Save > Error occurs 
![image](https://user-images.githubusercontent.com/47977411/53410102-ccfaac00-39fd-11e9-9735-488b9c07126a.png)

**Comment by ZawZawThein** [comment]
Changeset 9814

**Comment by jessa21** [comment]
checked.
