### ISSUE TITLE
SALES-Reports-Reports & Queries-Balance Sheet-Customer Invoice Listing (Lansdcape). Invoice Amt and GST amt column should be 2 decimal places

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#451]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/8f6968a7-4c21-4bd6-9576-2234e59340ec)

**Comment by ZawZawThein** [comment]
repx file: R21OPInvoiceLandscape.repx
Changeset: 13340

**Comment by KatrinaCagaanan** [comment]
Resolved
