### ISSUE TITLE
Procurement-Purchase-Operations-Order Processing-Purchase Order (SO). The line item did not follow the default GST of the product.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#453]
Created a new product GST:

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/6e5a5eb9-31de-46b8-a79d-ff14f8cf2862)

But when tried to enter in SO, did not call up the G_IM but G_TX7
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/43fd49ca-c35e-4de4-921d-328e9093d481)

Follow as GST logic:
1: MSTPRoduct
2.MSTCustomerSuppler
3.MSTDefaults

**Comment by zawuniqesolutions** [comment]
Same with Issue #455

**Comment by KatrinaCagaanan** [comment]
Hi @zawuniqesolutions,
I will re-open this ticket. 
*Testing the logic for GST. I removed the GST in MSTProduct so that the system will follow GST on MSTCustomerSupplier but the GSt becomes blank.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/570e2dc9-f647-4e46-8ad4-708477aa4af8)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/27931e94-2dbc-407c-ab8f-a32e15c485c3)


Should be GST Deemed Supplies
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/012e7a11-c235-4052-a497-afe624beabae)

**Comment by zawuniqesolutions** [comment]
Related with Issue #459 .

**PS.** Please remap GST Type in Supplier which you want to test.

**Comment by KatrinaCagaanan** [comment]
Resolved
