### ISSUE TITLE
Procurement-Purchase-Operations-Order Processing-Cash Invoice (SA). The line item did not follow the default GST of the product.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#454]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/044bb414-a3ee-46d8-b219-29cd609a6c1e)

GST logic:
1. get from MSTProduct (SalesGSTType) 
2. If 1 is NULL, get from MSTCustomerSupplier (GSTType) 
3. If 1 and 2 is NULL, get from MSTDefaults (DefaultGSTTypeCust)

**Comment by zawuniqesolutions** [comment]
Same with Issue #455

**Comment by KatrinaCagaanan** [comment]
Hi @zawuniqesolutions,

Will re-open this ticket.
Testing this logic:
Order of sequence for SALES Transaction 
1. get from MSTProduct (SalesGSTType) 
2. If 1 is NULL, get from MSTCustomerSupplier (GSTType) 
3. If 1 and 2 is NULL, get from MSTDefaults (DefaultGSTTypeCust)

*I removed the GST in MSTProduct
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/316cfbdc-e771-45ca-9285-f0e6ec47c729)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a3bb89d7-4863-4e8b-bf98-87ef986a9221)
But when I create SA, GST is blank.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/2de4c685-65bd-4235-8eac-cb0bff63911b)

Note: Kindly ensure to follow the next sequence logic, if MSTproduct is null and MSTCustomerSupplier is null, next is get from MSTDefaults.

**Comment by zawuniqesolutions** [comment]
Related with Issue #459 .

**PS.** Please remap GST Type in Supplier which you want to test.

**Comment by KatrinaCagaanan** [comment]
Resolved
