### ISSUE TITLE
Procurement-Purchase-Operations-Order Processing-Credit Invoice wth Deposit (SM). The line item did not follow the default GST of the product.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#455]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/71721d5e-81bb-4da4-9b2f-7e3c0071041a)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.
**Changeset 13360** 

**PS.** I already fixed other pages for that logic.

**Comment by KatrinaCagaanan** [comment]
Hi @zawuniqesolutions,

Will re-open this ticket.
Testing this logic:
Order of sequence for SALES Transaction 
1. get from MSTProduct (SalesGSTType) 
2. If 1 is NULL, get from MSTCustomerSupplier (GSTType) 
3. If 1 and 2 is NULL, get from MSTDefaults (DefaultGSTTypeCust)

*I removed the GST in MSTProduct
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/316cfbdc-e771-45ca-9285-f0e6ec47c729)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a3bb89d7-4863-4e8b-bf98-87ef986a9221)
But when I create SM, GST is blank.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/14b5db59-b846-4a21-87d7-4aa7f2a5163d)

Note: Kindly ensure to follow the next sequence logic, if MSTproduct is null and MSTCustomerSupplier is null, next is get from MSTDefaults.

**Comment by zawuniqesolutions** [comment]
Related with Issue #459 .

**PS.** Please remap GST Type in Supplier which you want to test.

**Comment by KatrinaCagaanan** [comment]
Resolved
