### ISSUE TITLE
SALES-Admin-Master Settings-Customer Maintenance. Suppliers can also be searched and called up in Customer Maintenance. by right, only customers can be called up and edited.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#457]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/ddd59fb8-7ab3-4d55-86f4-b9bb75b1ac30)

**Comment by ZawZawThein** [comment]
Changeset 13351
SQL : MSTCustomer_selectData.SQL

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein,

Still the same. the suppliers can still be seen in the customer maintenance
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/3c85d7a5-a2d3-45a7-a452-2731a82547f3)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/9adb4a92-01b1-4649-b7fc-40341716b3f8)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a078de9d-9950-4fe4-8867-3a6715c1b907)

**Comment by KatrinaCagaanan** [comment]
Resolved
