### ISSUE TITLE
SALES-Admin-MasterSettings-Customer Maintenance. GST Selection should only show active GST types for selection. Exclude Purchase GST types.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#458]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/ddbca6e5-b5fa-4168-93b8-c128d9e3d8d1)

Only those active Sales GST should appear for selection.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/9daaf19a-d23f-4525-8833-8864cb328bdd)

**Comment by ZawZawThein** [comment]
Changeset: 13352
Affected SQL: MSTCustomer_GetDataOptions.SQL

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein,

Still the same.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/9ac74bfa-cbda-4f21-9d52-3318fcd5784d)

**Comment by KatrinaCagaanan** [comment]
Resolved
