### ISSUE TITLE
Procurement-Admin-Master Settings-Supplier Maintenance. Only active purchase GST types should only appear for GST selection. Exclude Sales GST types.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#459]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/e399741d-6d84-454a-a020-66d78eafde51)

**Comment by zawuniqesolutions** [comment]
Waiting for publish 

**Changeset 13382**

**PS.** Please remap GST Type for Supplier which you want to test again.

**Comment by KatrinaCagaanan** [comment]
Resolved
