### ISSUE TITLE
Error: Can't save Daily Currency Rate by Date Table 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#46]
Add new daily currency rate table by date > save > error occurs. no entries saved . 
http://a21.sg:94/GeneralLedger/SMCurrencyRateByDate/220
![image](https://user-images.githubusercontent.com/47977411/53410959-44c9d600-3a00-11e9-8b9d-6bd2e8efe8b1.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9804

**Comment by jessa21** [comment]
Checked.
