### ISSUE TITLE
Procurement-Purchase-Operations-Order Processing-Purchase Invoice on GRN(SP). The line item did not follow the default GST of the product

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#461]
Scenario:
1. Create SN with Product P001 (MSTProductGST is G_IM
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/96a93769-2336-4541-a47c-96a6f553791e)

2. Load the SN to SP. But SP transaction GST is NA-NR. Should be G_IM.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/5b20e2f4-ccad-4f0a-8ca4-0dbe42423d53)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13383**

**Comment by KatrinaCagaanan** [comment]
Hi @zawuniqesolutions,

I will re-open this ticket. The GST in line detail is already correct but it seems the GST is not being updated in the GST total.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a10742ea-3860-4767-9ee8-f52a615be46d)

**Comment by KatrinaCagaanan** [comment]
Hi @Aungyetun991990 
I will re-open this one.
Testing GST sequence
1. get from MSTProduct (SalesGSTType/PurchaseGSTType) 
2. If 1 is NULL, get from MSTCustomerSupplier (GSTType) 
3. If 1 and 2 is NULL, get from MSTDefaults (DefaultGSTTypeCust)

-The SN and now follows the GST per MSTProduct. - tested, correct already.
-Now, I deleted the GST in MSTProduct, so system should get GST from MSTCustomer/Supplier - tested, not ok.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/76169eec-ccb9-41a5-8055-1cfafad1104c)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/aab581c4-9f6e-4f1f-8b41-7bfdd72c6173)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a3da144d-70d7-4ff5-8c83-e6413d7e4434)

**Comment by KatrinaCagaanan** [comment]
Resolved
