### ISSUE TITLE
FINANCE-Reports-Reports &Queries-General ledger Listing. The subtotal and grand total amounts should be in 2 decimal places

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#464]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/c10d8838-4839-4344-9a0e-c33ab6c89d19)

**Comment by ykauniqe** [comment]
pls test by using new record.

**Comment by KatrinaCagaanan** [comment]
Hi @Aungyetun991990  & @ykauniqe 
I will re-open this ticket. Issue persists.
Report subtotal and grand total are stil not in 2 decimal places.
I created a new transaction.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/84ee62c2-f84f-4e34-9b88-0865d26d5788)

**Comment by KatrinaCagaanan** [comment]
resolved
