### ISSUE TITLE
Procurement-Order Processing-Debit Note (SD)-GST INCLUSIVE. Cost captured in Stock Transaction listing and Stock Ledger should be without GST.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#466]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/7ecabdad-93ab-440f-874f-3afe8695ef2e)
But stock transaction listing shows S$100, which includes GST
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/5e96284c-e93b-43a4-b8bb-4ffe1f8ea14b)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/054057c0-10ef-4f33-9e5d-45dff0c22526)

**Comment by zawuniqesolutions** [comment]
Pending QA.

Hi @KatrinaCagaanan 
This issues was already fixed.
After edit line detail and saving again, the report value was correct.
Please try to test with another new transactions.
Thanks...

**Comment by KatrinaCagaanan** [comment]
Resolved
