### ISSUE TITLE
Bank Chq Type -  Forecast 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#47]
Cash Book > Maintenance > Bank Chq Type 
http://a21.sg:94/CashBank/SUBankChequeType/230

Select Tick or Y , IF Forecast is enabled 
Select Untick or N, IF Forecast is disabled 

Meanwhile, system allows to enter 1,2,3 ( alphabet) in order to activate Forecast. 
If null, system does not allow to save . 

![image](https://user-images.githubusercontent.com/47977411/53411796-70e65680-3a02-11e9-8ad0-21da0caca655.png)

**Comment by ZawZawThein** [comment]
Changeset 9855

**Comment by jessa21** [comment]
done
