### ISSUE TITLE
SALES-Order Processing-Customer Sales Order (CO)- Filter Edit Screen shows blank although created CO transactions already

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#470]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/bd991def-4259-40c4-a685-e52ff54ad8f1)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b0a55347-8a9d-493b-a61f-96c7a4fff538)

**Comment by ZawZawThein** [comment]
Changeset 13478
Procedure: GetTransactionByWildCards_A21OPOrder.SQL

**Comment by KatrinaCagaanan** [comment]
Resolved
