### ISSUE TITLE
SALES-Procurement-Order Processing- Invoice on DO (CI). Was able to load CY with GST exclusive and GST inclusive in 1 CI, causing the GST to be wrong

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#471]
Scenario:
1. Created CO-CY with GST Exclusive
2. Created CO-CY with GST Inclusive
3. Tried to load both CY in 1 CI. System allows. By right, does not allow and should have a validation. 
If the 1st CY loaded is GST exclusive, the rest of the CY should be GST exclusive as well and vice versa.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/5939e5af-5c64-4c13-b69c-87236406161a)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/8ec983a7-f9d0-4d15-a7a0-28c27e50ccea)

**Comment by ZawZawThein** [comment]
Changeset: 13492,13493

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein ,

The system still allows exclusive GST and inclusive GST in 1 CI.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/db941d34-7525-4ffd-be9a-45ad96a03bfa)

But I noticed that if I load the CY35 (GST exclusive) first, then there's validation cannot load the CY34 (Inclusive). But if I load CY34 first, then I am able to load CY35 as well.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/0bc30f37-ef80-4a00-a093-a6d97a7ce194)

**Comment by KatrinaCagaanan** [comment]
Resolved
