### ISSUE TITLE
PROCUREMENT-Procurement-Order Processing- Invoice on GRN(SP). Was able to load SN/SG with GST exclusive and GST inclusive in 1 SP, causing the GST to be wrong

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#473]
Scenario:
1. Created SO-SG with GST Exclusive
2. Created SO-SG with GST Inclusive
3. Tried to load both SG in 1 SP. System allows. By right, does not allow and should have a validation.
If the 1st SG/SN loaded is GST exclusive, the rest of the SG/SN should be GST exclusive as well and vice versa.

**Comment by ykauniqe** [comment]
related with ticket no #471

**Comment by zawuniqesolutions** [comment]
Waiting for publish.
**Changeset 13483**

Hi @KatrinaCagaanan 
There is no GSTInc condition in GRN operations.
Please confirm with Clarity. 

Window Base SourceCode
----------------------------
Function's Name => LoadDefaultsGRN

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13522**

**Comment by KatrinaCagaanan** [comment]
Hi @zawuniqesolutions ,

Not so sure what do you mean by no GST inc in GRN but please read carefully the scenario I mentioned. It can come from SO-SG-SP.
![image](https://user-images.githubusercontent.com/47963355/70371277-f42ac600-190b-11ea-9e72-5d2a09aabfc9.png)
To illustrate:
![image](https://user-images.githubusercontent.com/47963355/70371296-36ec9e00-190c-11ea-9d90-0645f6252c98.png)

![image](https://user-images.githubusercontent.com/47963355/70371313-67343c80-190c-11ea-86f6-30c35c80fc94.png)
![image](https://user-images.githubusercontent.com/47963355/70371347-c003d500-190c-11ea-99bd-586886bee225.png)

**Comment by KatrinaCagaanan** [comment]
Resolved
