### ISSUE TITLE
SALES-OrderProcessing-Operations-Debit Note(CD). Wrong GL Posting - Stock a/c and COS/Closing Stock A/c not posted. (Please do for Cost of Sales Posting and Closing Stock Posting)

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#474]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/002be4be-777d-40bd-8aae-dee5a997c037)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/918fc952-ac63-4058-b8a5-f21970257309)

**Comment by ykauniqe** [comment]
related ticket #429

**Comment by ZawZawThein** [comment]
Changeset: 13584

**Comment by KatrinaCagaanan** [comment]
Resolved
