### ISSUE TITLE
SALES-OrderProcessing-Operations-Goods Return Credit Note (CC). GST in subtotal is not being updated.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#475]
Scenario:
-Line GST is 7% but the subtotal GST is still 0.

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/e2dfa095-4258-4a8f-96a5-b4b5209dc275)

**Comment by ZawZawThein** [comment]
Changeset: 13513
13512

**Comment by KatrinaCagaanan** [comment]
Resolved
