### ISSUE TITLE
SALES-Order Processing-Operations-Goods Returned Credit Note(CC)- CC does not appear in customer invoice listing reports.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#476]
Created CC transaction does not appear in the customer invoice listing report
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/692bc559-f9ba-4187-a99d-b27e19834161)

**Comment by ZawZawThein** [comment]
Changeset 13556.
Please kindly check with new transaction.

**Comment by KatrinaCagaanan** [comment]
Resolved
