### ISSUE TITLE
SALES-OrderProcessing-Operations-Debit Note(CD) & Goods returned credit note (CC). CD and CC does not follow the GST logic sequence. I removed the GST in MSTProduct and it should get the GST in MSTCustomerSupplier but it does not do so. 

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#477]
GST Logic:
1. GST gets from MSTProduct
2. If #1 is null, get from MSTCustomerSupplier
3. If #2 is null, get from system defaults

Scenario:
-Removed the GST in MSTProduct
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/d49ef801-39fd-41df-bd0c-049fa675fa73)
-Create CC and CD and it should get GST from MSTCUStomerSupplier
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/00ab6251-53e6-4762-a0a1-a6262f6a39ea)
But it seems it does not follow the MSTCustomerSupplier
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/11c945be-a53c-4fdd-8909-b09e988e7ff8)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/58f43071-eda4-472b-93d6-aba122b9e3e7)

**Comment by ZawZawThein** [comment]
Changeset: 13535,13536

**Comment by KatrinaCagaanan** [comment]
Resolved
