### ISSUE TITLE
SALES-Order Processing-Operations (CO,CE,CR,CA,CM,CC,CD,CX,CY,CI) -Customer master from transaction does not show info mandatory info

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#478]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/5b669d60-8ef8-49ed-ba70-ad4fb2ffec44)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/99a5fb08-dd57-4070-9a46-df9fa75cbf19)
But when access customer maintenance from Sales->Admin->Master Settings->Customer Maintenance.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/3c290e9a-5ee9-49c3-818b-c1acdc7b85b9)
*Please do for all Sales transactions

**Comment by ZawZawThein** [comment]
Changeset 13516

**Comment by KatrinaCagaanan** [comment]
CO Still the same Customer- Testing:
![image](https://user-images.githubusercontent.com/47963355/70299423-d6882e80-182f-11ea-9271-36f642b1e3a7.png)
CE
![image](https://user-images.githubusercontent.com/47963355/70299522-15b67f80-1830-11ea-87f9-2d58ffc20c3e.png)
CR
![image](https://user-images.githubusercontent.com/47963355/70299627-662ddd00-1830-11ea-9bac-3ffaa1087d91.png)
CA
![image](https://user-images.githubusercontent.com/47963355/70299695-95444e80-1830-11ea-9c21-f240a1ac29ab.png)
Please do for all sales transactions -CM,CC,CD,CX, CY, CU

**Comment by ZawZawThein** [comment]
Changeset 13591

**Comment by KatrinaCagaanan** [comment]
Resolved
