### ISSUE TITLE
SALES-Order Processing-Operations (CO,CE,CR,CA,CM,CC,CD,CX,CY,CI). PDSU in the transaction does not follow the customer maintenance default PDSU.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#479]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/3ddb52a0-815a-4dae-8075-a4ced51c7699)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/96463b3c-a6d7-4764-8723-b9a6e99004dc)
*Pls do for all Sales Transactions

**Comment by ZawZawThein** [comment]
Changeset 13542

**Comment by KatrinaCagaanan** [comment]
Resolved
