### ISSUE TITLE
Bank Cheque Management 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#48]
The back chq transaction is not  working . Enhancement is required. 
http://a21.sg:94/CashBank/A21BankCheque/220
![image](https://user-images.githubusercontent.com/47977411/53412282-e69ef200-3a03-11e9-9fde-733ad44d9907.png)

http://a21.sg:94/CashBank/U21BankChequeDashBoard/240
![image](https://user-images.githubusercontent.com/47977411/53412634-d3d8ed00-3a04-11e9-9161-0af83c332de7.png)

@jameslee888sg  @ykauniqe @ErwinMetra  - As discussed with James, we will enhance bank chq mgmt later.

**Comment by ZawZawThein** [comment]
Changeset 10039
Changeset 10040

select * from U21Menus where ControllersName = 'A21BankCheque'

**Comment by ZawZawThein** [comment]
**We already discus with TT. This ticket need to hold. 
It is need to create RR transaction.Noted with Thanks**

**Comment by jessa21** [comment]
Noted 
@jameslee888sg  - FYI. R&D will enhance the bank chq mgmt in phase 2.
