### ISSUE TITLE
SALES-Reports Queries-Sales Analysis reports-Sales Analysis Product Wise product wise (landscape) (Stk Bal) - Under construction

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#480]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/5979716f-8e6b-47e3-a1bc-1b80fa8f8c99)

**Comment by ZawZawThein** [comment]
Changeset 13558
DataSet: R21MISSalesProductLStock.xsd

**Comment by KatrinaCagaanan** [comment]
Resolved
