### ISSUE TITLE
Procurement-Purchase-Operations-Purchase Order (SO). System does not allow  to change currency and exchange rate even though user maintenance setting is allowed to change currency and exchange rate in SO.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#484]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/ee748d9e-3615-4f33-999e-7b12f458f26d)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/67a0ef08-a81d-4394-a129-ea3e2cae6b94)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13632**

**Comment by KatrinaCagaanan** [comment]
Resolved
