### ISSUE TITLE
Procurement-Admin-Supplier Maintenance. Can still access price table/product pricing even though user settings is untick for "allowed to access price table in supplier master".

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#485]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/52b5bf5c-b6f1-47d1-86be-e0d923c9359b)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/edebefdc-e2c1-4ebd-af84-bd66ece29e20)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/080b546e-f708-494a-8a8d-a58639e766a0)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13682**

**Comment by KatrinaCagaanan** [comment]
Hi @zawuniqesolutions 
Cannot test.  Ticket #523 , supplier maintenance is empty.

**Comment by KatrinaCagaanan** [comment]
Hi @zawuniqesolutions ,
Will need to re-open this. You hide the whole price and location tab. The Price should only be hidden not the Location. So when the option is untick, the tab becomes "location" tab only not price and location tab.
![image](https://user-images.githubusercontent.com/47963355/70873927-cf5cdf80-1fea-11ea-9e26-439024fd3955.png)
![image](https://user-images.githubusercontent.com/47963355/70873976-04693200-1feb-11ea-9a33-009aff439146.png)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13749**

**Comment by KatrinaCagaanan** [comment]
Resolved
