### ISSUE TITLE
Warehouse-Stk Transaction-Inquiry-Stock Status Query. Able to access Qty On PO even though user settings set not allowed

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#488]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/1e37b5d1-a5cc-4ba5-aafb-2790033bf26b)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b3cbe34d-1a04-4a25-8001-a8f78bad281b)

**Comment by ZawZawThein** [comment]
Changeset 13703
Affected file:  Q21IMStockStatus_Script.cshtml

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein ,
Will re-open this ticket. Still the same, can still access QTY on PO.
![image](https://user-images.githubusercontent.com/47963355/70786626-099a6700-1dc8-11ea-8822-89df33a69fa9.png)
![image](https://user-images.githubusercontent.com/47963355/70786665-259e0880-1dc8-11ea-8361-63a996b705fb.png)

**Comment by ZawZawThein** [comment]
Changeset 13731
Affected file: Q21IMStockStatusController

**Comment by KatrinaCagaanan** [comment]
Resolved
