### ISSUE TITLE
Procurement-OrderProcessing-Inquiry-Supplier Status Query-Pending order. Cannot drill down to transaction in Pending Order

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#489]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/cd5e4dcf-ef9d-4746-9428-7b40180c9ff2)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/2cd3d806-39f9-4b25-b6ef-7cdb23bfe523)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13697**

**Comment by KatrinaCagaanan** [comment]
Resolved
