### ISSUE TITLE
Procurement-Order Processing-Supplier Bills- GRN Direct (SN). The PDSU does not follow default PDSU of supplier. Do for all Purchase Transaction (SO,SE,SI,SM,SA,SG,SP)

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#490]
Scenario
-Created SN
-Check the PDSU but PDSU is empty. SHould follow the default PDSU of Supplier

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/2c27a2bf-391d-4e0b-bc9f-4da9bf659b7d)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/6a914d3f-817e-4b37-92c7-94be03f36605)

**Comment by ykauniqe** [comment]
Order of sequence for Default PDSU
system pick up date from PDSU
1. get from FormSetting  
2. If 1 is NULL, get from MSTCustomerSupplier 
3. If 1 and 2 is NULL, get from MSTDefaults

**Comment by ykauniqe** [comment]
Order of sequence for Default PDSU
system will be picked up data from PDSU

get from FormSetting
If 1 is NULL, get from MSTCustomerSupplier
If 1 and 2 is NULL, get from MSTDefaults

**Comment by ykauniqe** [comment]
Order of sequence for Default PDSU
system will be picked up data from PDSU
1. get from FormSetting  
2. If 1 is NULL, get from MSTCustomerSupplier 
3. If 1 and 2 is NULL, get from MSTDefaults

**Comment by ykauniqe** [comment]
order sequence for PDSU. Kindly proceed based on the following order sequence for PDSU:
1. Get from MSTCustomerSupplier 
2. If 1 is NULL, get from FormSetting  
3. If 1 and 2 is NULL, get from MSTDefaults

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13736**

**Comment by KatrinaCagaanan** [comment]
Resolved
