### ISSUE TITLE
Procurement-Order Processing-Supplier Bills- (SG & SN). No "create invoice" button. Cannot create directly from SG and SN.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#491]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/144bc643-f97b-4e9f-a68b-564a6f42d2dc)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/04313a81-3c8e-4f1f-9115-475a5a2e53e3)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/722429ce-c496-4205-b7dd-e49dca656e77)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13655**

**Comment by KatrinaCagaanan** [comment]
Resolved
