### ISSUE TITLE
Procurement-Order Processing-Supplier Bills- (SG & SN). Cannot change the DATE for SG/SN  after invoice (allowed to change per user settings).

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#493]
Scenario:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/022048e9-f5c2-4cb9-91e5-dc53fec8ea16)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/acf9d718-be12-4ee6-a103-82e4ece38400)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13668**

**Comment by KatrinaCagaanan** [comment]
Resolved
