### ISSUE TITLE
Procurement-Purchase-Operations-Purchase Order (SO). Untick option in user settings to not allow edit SO after GRN/Invoice but system still allows me to edit SO.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#494]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/d84ff867-c5c5-452e-a6ad-e476d8bc09ec)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/64efccca-426d-4779-91f9-09fb1eca2489)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13678**

**Comment by KatrinaCagaanan** [comment]
Resolved
