### ISSUE TITLE
Procurement-Admin-MasterSettings-Supplier Maintenance. System allows to edit/change supplier name even though I untick option in user maintenance to allow change.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#495]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/67d6d732-80fa-458b-9284-bc83da00ed8f)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/1351dc02-4e29-4881-b231-9bd6eb4c96ca)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13698**

**Comment by KatrinaCagaanan** [comment]
Hi @zawuniqesolutions ,
I cannot test this now. Waiting for ticket no 523. Currently, supplier maintenance is blank.

**Comment by KatrinaCagaanan** [comment]
resolved
