### ISSUE TITLE
Sales=>Admin=>CustomerImport Cannot click the import button.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#498]
![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/c5244df9-8b66-4b02-af71-9b6d55e09b5c)

**Comment by zeusa2000** [comment]
Trying to import as of now and still cannot.
![image](https://user-images.githubusercontent.com/51438852/70686043-0e86ea00-1ce6-11ea-80fa-27b2a6a9ffb0.png)

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/70962434-326c7600-20c0-11ea-838b-7fc353049117.png)

Trying to re-upload again but cannot due to currency error log but as per checking the currency format is existing on excel format.

**Comment by ykauniqe** [comment]
related ticket #497

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/70963976-14eddb00-20c5-11ea-9527-626ea51eb2f0.png)
Can upload now but Typed wrongly the account type and account group but successfully uploaded the excel and not in the customer maintenance.

**Comment by zeusa2000** [comment]
Trying to upload but it's saying truncated but as per double check there is no over character.

![image](https://user-images.githubusercontent.com/51438852/71466124-95b18300-27f9-11ea-89d9-24ca7f2c388b.png)

**Comment by zeusa2000** [comment]
Upload successful after changing the country code from Philippines - PHL and Myanmar - MM
