### ISSUE TITLE
FINANCE-Receivables-Receipt Transaction. 1) Filter customer includes supplier lisst, by right only customer list. 2) Search/filter customer not working.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#499]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/45d3e390-9964-4b08-b58c-56cfe6aa9c33)

**Comment by ZawZawThein** [comment]
Changeset 13638
Affected file: A21ARTransaction_Script.cshtml

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein ,

I will re-open this ticket. Left with #3 issue:
![image](https://user-images.githubusercontent.com/47963355/70581604-a9060100-1bf2-11ea-9136-7c3df01d536a.png)

**Comment by ZawZawThein** [comment]
Changeset 13666

**Comment by KatrinaCagaanan** [comment]
Resolved
