### ISSUE TITLE
FINANCE-Receivables-Receipt Transaction. Previous button not working. Cannot go back to previous transaction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#500]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/ccdcc256-e48b-4741-8e7d-5902448d231f)

**Comment by ZawZawThein** [comment]
Changeset 13642
GetTransNumbers in CommonController.cs

**Comment by KatrinaCagaanan** [comment]
Resolved

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein ,

I will re-open this ticket. Seems the back button does not work again.
Scenario:
-Create new transaction and SAVE for example RR30.
-Once click SAVE, the screen will generate RR31 for new record and cannot go back to previous transaction  RR30 already using the back button.
![image](https://user-images.githubusercontent.com/47963355/70605288-336f5480-1c35-11ea-9de8-b3e9e6239578.png)

**Comment by ZawZawThein** [comment]
Changeset 13679

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein ,
Will need to re-open again.
I can use the back button already but instead of going back to previous transaction. It goes 2 transactions back.
Scenario:
-Created RR 34 and SAVE.
-Upon saving its a new transaction RR35 already. I click the previous transaction button but it goes to RR33, should be RR34.

**Comment by KatrinaCagaanan** [comment]
Resolved
