### ISSUE TITLE
FINANCE-Receivables-Receipt Transaction (RR). Wrong GL posting - unbalance GL transaction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#502]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/197dd60e-973d-4a47-9532-4f88f09812b6)

**Comment by ZawZawThein** [comment]
Changeset: 13665

**Comment by ykauniqe** [comment]
Hi, @KatrinaCagaanan , pls test new record.

**Comment by KatrinaCagaanan** [comment]
Resolved
