### ISSUE TITLE
FINANCE-Receivables-Receipt Transaction (RR). PDSU of RR does not follow the customer default PDSU.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#503]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/68714674-1e4e-4862-bab7-9cd11efa1e87)

**Comment by ZawZawThein** [comment]
It is related with #479 
@ykauniqe , What is first priority is form Setting or Customer maintenance ?

**Comment by ykauniqe** [comment]
order sequence for PDSU. Kindly proceed based on the following order sequence for PDSU:
1. Get from MSTCustomerSupplier 
2. If 1 is NULL, get from FormSetting  
3. If 1 and 2 is NULL, get from MSTDefaults

**Comment by ZawZawThein** [comment]
Changeset 13718

**Comment by KatrinaCagaanan** [comment]
Resolved
