### ISSUE TITLE
FINANCE-Receivables-Receipt Transaction (RR). Some fields in Customer master from RR transaction are empty. 

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#505]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/0763cf20-0642-48ce-ad97-c192bc9bb67d)
But customer maintenance from SALES-Admn-Master-Customer Maintenance have been filled up.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/931a577f-dbd8-47a9-8cc7-3b5422d57254)

**Comment by ZawZawThein** [comment]
Changeset 13644

**Comment by KatrinaCagaanan** [comment]
Resolved
