### ISSUE TITLE
FINANCE-Receivables-Reports-Reports & Queries-Customer-Customer Ledger. Wrong Customer ledger info

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#506]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b3c938f1-04f0-44f3-a53e-32b8188c24aa)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/62650b57-8f7a-444d-a2af-0c9bee8271d9)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/02dcbf0f-439a-4f6c-b7fd-171396dcf582)

**Comment by ZawZawThein** [comment]
Changeset 13676
Affected file : A21Operations.cs
Note: //Note ( not insert data to A21ARAPTransactionHeader table from (Delivery Order Direct (CU) and Free Text Invoice(CX))

**Comment by KatrinaCagaanan** [comment]
Resolved
