### ISSUE TITLE
Server Error in '/' application

### ISSUE THREAD

**Issue by roxannebernabe** [a2000-erp-team/WEBERP#51]
Payables -> Reports -> Document Printing
![error](https://user-images.githubusercontent.com/47958190/53456811-c2c2c700-3a6a-11e9-9096-4ae191bfefd6.PNG)

**Comment by ZawZawThein** [comment]
Changeset: 9883

**Comment by ZawZawThein** [comment]
Changeset 9977 >> PI dataset
Changeset 9978  >> PC dataset
Changeset 9979
Changeset 9980

[PI] Supplier Invoice
Changeset 10013

Payment Voucher [PV]
Changeset 10017
