### ISSUE TITLE
FINANCE-Payable-Operations-Payable Transaction (AP). Exclude customers in the filter list, should only have suppliers

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#510]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/28b357f7-1ce8-4850-a0db-cbe667d30394)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13661**

**Comment by KatrinaCagaanan** [comment]
Resolved
