### ISSUE TITLE
FINANCE-Payable-Operations-Payable Transaction (AP). Not able to delete line item.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#511]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/df01a4cc-106f-4ede-a95d-3454d0e82fde)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

Included change set with Issue #512

**Comment by KatrinaCagaanan** [comment]
Resolved
