### ISSUE TITLE
FINANCE-Payable-Operations-Payable Transaction (AP). Make the Bank field (like supplier) and cheque no field as well a mandatory field before proceeding to line detail.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#512]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/609ace53-0fcf-494a-a210-eb2365ae2112)

Can also follow, RR screen header, wherein the Bank field and cheque no field are part of the main Header for uniformity purposes.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/3d84e5c6-7426-45e1-b232-a1e28637a63c)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13663**

**Comment by KatrinaCagaanan** [comment]
Resolved
