### ISSUE TITLE
FINANCE-Payable-Operations-Payable Transaction (AP). Back button to go back to previous transaction goes to 1st transaction (PV1), instead of the previous latest transaction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#513]
Scenario:
-Create a PV 26 and SAVE.
-Click  the previous button to go back to previous latest transaction which is PV26, but it goes to PV1 instead.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/c09685eb-5f71-4df2-8eb0-dccd7f2cee17)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/045a8070-7d9a-4783-a2f7-df207228812c)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13699**

**Comment by KatrinaCagaanan** [comment]
Hi @zawuniqesolutions , Will need to re-open this ticket. If create new transaction and click previous button, the PV becomes blank.
Scenario:
-Created new PV transaction 30 and click SAVE:
![image](https://user-images.githubusercontent.com/47963355/70771996-13af6c00-1dae-11ea-8dac-f7fa5439b82f.png)
It goes to new transaction PV31:
![image](https://user-images.githubusercontent.com/47963355/70772054-46596480-1dae-11ea-8362-3ad301361cf2.png)
![image](https://user-images.githubusercontent.com/47963355/70772077-5c672500-1dae-11ea-9a19-85e123bea815.png)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13734**

**Comment by KatrinaCagaanan** [comment]
Resolved
