### ISSUE TITLE
FINANCE-Payable-Operations-Payable Transaction (AP). Relationship of allocation of PV to the invoice and Invoice does not show in Supplier ledger even after allocation

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#514]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a4bb6adf-24d0-406f-90cb-0bc7306524f0)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/bf2b4f53-04b9-4aa1-b3ee-98e60ceb4ac7)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/7c980b95-a56b-4728-ac6d-28400eae6a0f)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13732**

**Comment by KatrinaCagaanan** [comment]
Resolved
