### ISSUE TITLE
HOME-System manager-System Utilities-System Settings-Other tab. Untick "Allow GST in receipts and Payments, GST portion should be hidden in PV

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#515]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/92c78ecb-a040-4a07-9ff7-86a61261bb26)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/8e8a6ac6-46da-4cca-95c7-32e938be8034)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/d0fb2ef2-da8a-442b-b4fc-497872441b09)

**Comment by zawuniqesolutions** [comment]
Waiting for publish for AP.
Left to fix in AR part.

**Changeset 13701**

**Comment by KatrinaCagaanan** [comment]
Resolved
