### ISSUE TITLE
FINANCE-Receivables-Receipt Transaction (RR). Able to delete line details even with allocation. Kindly have a validation for RR that cannot delete line detail if there's allocation. Need to delete allocation first.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#516]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/5dc5655e-c8c5-42d0-a353-6640122f17e7)

Sample prompt in Clarity:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/62c260ac-8ff3-4ef3-a344-59b49264f9f8)

**Comment by ZawZawThein** [comment]
Changeset 13683

**Comment by KatrinaCagaanan** [comment]
Resolved
