### ISSUE TITLE
FINANCE-Payable-Operations-Payable Transaction (AP). Was able to delete line details even with allocation.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#517]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/95d9be3f-9e00-4fc5-b3dc-d76dde47fcd8)

Sample prompt validation in Clarity:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/e9973739-6023-4373-8d86-d17c68a6ff38)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13704**

**Comment by KatrinaCagaanan** [comment]
Resolved
