### ISSUE TITLE
FINANCE-Receivables-Receipt Transaction (RR). Kindly remove CU,CX, and CY from the allocation list. Only invoices should show.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#518]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/c2bf032e-63fe-48ea-9181-80099c1077e9)

**Comment by ZawZawThein** [comment]
Changeset 13684
Affected file: A21ARTransaction_GetOptTrnTypeAllc.SQL

**Comment by KatrinaCagaanan** [comment]
Resolved
