### ISSUE TITLE
FINANCE-Receivables-Receipt Transaction (RR). Wrong posting of exchange gain/loss for foreign currency transaction

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#519]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/c8f9195c-74b2-4f36-b6ef-e5dae95b9e95)

GL Posting:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/53d4d233-73c0-4608-a3ff-f84353b1e1a5)

Should be posting:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/c9c95eab-a447-41ad-9b19-d3f50c787740)

**Comment by ZawZawThein** [comment]
Changeset 13700
Affected file: A21ARTransactionModel.cs

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein ,
Need to re-open this ticket. Still the same. I created new transactions CR476 and RR39 with the same scenario - CR rate is 1.3 and RR rate is 1.4 with gain of 10.70. Still wrong psoting.
![image](https://user-images.githubusercontent.com/47963355/70789091-55034400-1dcd-11ea-8a8f-422669eba17d.png)
![image](https://user-images.githubusercontent.com/47963355/70789151-719f7c00-1dcd-11ea-8154-a39a78e44c32.png)

Should be posting:
![image](https://user-images.githubusercontent.com/47963355/70789204-867c0f80-1dcd-11ea-9733-ae50afd5c045.png)

**Comment by KatrinaCagaanan** [comment]
Resolved
