### ISSUE TITLE
Payables[Page Under Construction]

### ISSUE THREAD

**Issue by roxannebernabe** [a2000-erp-team/WEBERP#52]
Payables -> Reports ->GL & AP Diagnostics

![error](https://user-images.githubusercontent.com/47958190/53456904-29e07b80-3a6b-11e9-8e8c-36d2c1a19f70.PNG)

**Comment by ZawZawThein** [comment]
Changeset 9818
Changeset 9819
Changeset 9820
Changeset 9822,9839

**Comment by ZawZawThein** [comment]
Please run this Script

alter function [dbo].[CheckAPAgeing](
@Company varchar(2)
,@FDate date
,@TDate date
) returns table return
SELECT DISTINCT
	A21GLTransactionHeader.TrnDate,
	A21GLTransactionHeader.TrnType,
	A21GLTransactionHeader.TrnNo,
	A21ARAPTransactionHeader.DebitAmount,
	A21ARAPTransactionHeader.CreditAmount,
	[CreditAmount] - [DebitAmount] AS Balance,
	(
		[CreditAmount] - [DebitAmount]
	) * [ExchangeRate] + ([CreditBase] - [DebitBase]) AS BalanceB,
	A21GLTransactionHeader.Currency,
	Abs(
		(
			[CreditAmount] - [DebitAmount]
		) * [ExchangeRate] + ([CreditBase] - [DebitBase])
	) AS BAL,
	A21GLTransactionHeader.Code,A21GLTransactionHeader.CrtUser
FROM
	A21GLTransactionHeader
LEFT JOIN A21ARAPTransactionHeader ON (
	A21GLTransactionHeader.TrnNo = A21ARAPTransactionHeader.TrnNo
)
AND (
	A21GLTransactionHeader.TrnType = A21ARAPTransactionHeader.TrnType
)
AND (
	A21GLTransactionHeader.Company = A21ARAPTransactionHeader.Company
)
INNER JOIN A21OPInvoiceDetail ON (A21GLTransactionHeader.TrnNo=A21OPInvoiceDetail.TrnNo) AND (A21GLTransactionHeader.TrnType=A21OPInvoiceDetail.TrnType) 
AND (A21GLTransactionHeader.Company=A21OPInvoiceDetail.Company)
WHERE
	(
		(
			(
				A21GLTransactionHeader.TrnDate
			) >= @FDate
			AND (
				A21GLTransactionHeader.TrnDate
			) <= @TDate
		)
		AND (
			(
				Abs(
					(
						[CreditAmount] - [DebitAmount]
					) * [ExchangeRate] + ([CreditBase] - [DebitBase])
				)
			) >= 0.001
		)
		AND (
			(
				A21GLTransactionHeader.Company
			) = @Company
		)
		AND (
			(
				A21GLTransactionHeader.TrnGrp
			) = 'S'
			OR (
				A21GLTransactionHeader.TrnGrp
			) = 'P'
		)
	)
OR (
	(
		(
			A21GLTransactionHeader.TrnGrp
		) = 'S'
	)
	AND (
		(
			A21ARAPTransactionHeader.TrnType
		) IS NULL
	)
);

**Comment by jessa21** [comment]
Diagnostic works OK
