### ISSUE TITLE
FINANCE-Receivables-Receipt Transaction (RR).  2nd line detail automatically adds when accepts the 1st row in RR.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#521]
Scenario:
-Add line item in RR
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/ab87d2c9-2da7-4132-9f8b-fdf422928fb6)
-Click accepts row then the 2nd line item comes out.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b662a1aa-16f5-4a5c-b13a-c628ca95bbb0)

**Comment by ZawZawThein** [comment]
Changeset 13706

**Comment by KatrinaCagaanan** [comment]
resolved
