### ISSUE TITLE
FINANCE-Receivables-Receipt Transaction (RR).  Batch Allocation window - freezed the allocation/balance totals.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#522]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/561c0cf1-65d4-4629-b217-bef514c82fdc)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/e6534d39-745a-4485-b3ea-4dcb74f98e07)

**Comment by ZawZawThein** [comment]
Changeset 13717

**Comment by KatrinaCagaanan** [comment]
Resolved
