### ISSUE TITLE
Procurement-Admin-Supplier Maintenance. Supplier Maintenance is blank/empty. Cannot add/edit Supplier.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#523]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/299c4a4f-1419-4565-8904-2221af0e01a2)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/b3b23cf0-6e39-4044-83cc-a07a31576392)

**Comment by ZawZawThein** [comment]
Changeset: 13730

**Comment by KatrinaCagaanan** [comment]
Resolved
