### ISSUE TITLE
HOME-System manager-System Utilities-System Settings-Other tab. Untick "Allow GST in receipts and Payments, GST portion should be hidden in RR

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#525]
![image](https://user-images.githubusercontent.com/47963355/70692803-1dc26380-1cf7-11ea-935c-27104b8c08d9.png)

![image](https://user-images.githubusercontent.com/47963355/70692822-27e46200-1cf7-11ea-8799-72d9e0909e72.png)

**Comment by ykauniqe** [comment]
related ticket #515

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein ,

Will re-open this ticket. Still can see the GST portion even I untick the option.

![image](https://user-images.githubusercontent.com/47963355/70762076-50696c00-1d8a-11ea-85bb-02d23562c45a.png)

![image](https://user-images.githubusercontent.com/47963355/70762241-dedded80-1d8a-11ea-8601-6b1bae42c5d5.png)

**Comment by KatrinaCagaanan** [comment]
Resolved
