### ISSUE TITLE
FINANCE-Payable-Operations-Payable Transaction (AP). Wrong green check indication for deleted PV transaction. Deleted PV transaction should also be red check since its also not allocated.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#526]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/50738b73-de36-4c00-a6e6-212f38813489)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/0d5d69db-7a34-48a3-8ec5-944999a49a76)

**Comment by zawuniqesolutions** [comment]
Hi @KatrinaCagaanan 
That was already fixed, please check again.
Same with Issue #527.

**Comment by KatrinaCagaanan** [comment]
Resolved
