### ISSUE TITLE
FINANCE-Receivable-Operations-Receivable. Wrong green check indication for deleted RR transaction. Deleted RR transaction should also be red check since its also not allocated. 

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#527]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/fe35c9ee-7f23-43f9-986b-1bf142504799)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/3fc74813-f536-4145-b819-992b0373b166)

**Comment by ZawZawThein** [comment]
Changeset 13733
Affected file: PostingTransaction.cs

**Comment by KatrinaCagaanan** [comment]
Resolved
