### ISSUE TITLE
FINANCE-Payable-Operations-Payable Transaction (AP). Error when saving PV transaction. Prompting to select GST but PV is a payment and no GST.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#528]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/e666bb9c-982c-4e1d-ac22-f44b520bb9e2)
Didn't tick the GST applicable bec payment don't have GST.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/340e07d0-7524-41df-81e3-0ef12f25d77b)

**Comment by zawuniqesolutions** [comment]
Hi @KatrinaCagaanan 

![image](https://user-images.githubusercontent.com/47886892/70878523-3c26a880-1ff0-11ea-8fb3-f374d688f4f2.png)

**Comment by KatrinaCagaanan** [comment]
@zawuniqesolutions , ok. I know that setting in system settings, thanks. Previously that settings was untick, just kindly check whether that option is becoming auto tick if your doing updates. I will close this now. :)
