### ISSUE TITLE
Procurement-Reports Queries-Reports&Queries-Supplier Invoice Listing. SC Transaction is being add up in the supplier listing. SC should be a deduction from the list since its a return.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#529]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/4db896bb-4159-4b0a-992c-d6de45e8bcef)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.
P.S - Need to run DBScript file.

**Changeset 13800**

**Comment by KatrinaCagaanan** [comment]
Resolved
