### ISSUE TITLE
Message prompt "Please fill trntype, trn no when creating Cash Bank Book

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#53]
Go Finance > Cash Book > Cash Bank Book

Scenario 1: Creation of new CASH BANK BOOK
Create of CASH BANK BOOK
Select Bank
-Select PDSU
-Select Currency
-Key-IN Payee
Add Details
-Click  detail
-Message prompt "Please fill trntype, trn no
Result : NOT CORRECT
![image](https://user-images.githubusercontent.com/47963668/53470287-1c8fb500-3a9c-11e9-9155-7115f786a19b.png)

**Comment by ZawZawThein** [comment]
**Changeset: 9922
Affected file: Areas\CashBank\Views\A21GLCashBank\A21GLCashBank_Script.cshtml**

**Comment by jessa21** [comment]
@ZawZawThein 

What is "the number setting" for? 
The date picker / calendar prompt when open cash bank screen 

![image](https://user-images.githubusercontent.com/47977411/56013527-b0070780-5d23-11e9-90e6-c2b5101eae0f.png)
