### ISSUE TITLE
Procurement->Reports Queries->reports&queries-> GRN Listing reports. Cannot find GRN Listing reports.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#531]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/dd7984c4-e1bc-4156-aece-aaa6dd204d7a)

In Clarity, GRN Reports is here:

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/e4484230-c13b-4917-a993-88de1bcdf778)

**Comment by ZawZawThein** [comment]
Changeset 13779

**Comment by KatrinaCagaanan** [comment]
Resolved
