### ISSUE TITLE
Finance-Payables-Operations-Payable Transaction (AP). Should not be able to allocation the same transaction to itself. For example, PV34 to PV34.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#532]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/ca66333c-592a-4c42-8094-f34519e5e28a)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.
P.S - Need to run DBScript file.

**Changeset 13797**

**Comment by KatrinaCagaanan** [comment]
Resolved
