### ISSUE TITLE
Cannot Save transaction message prompt 

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#54]

**Comment by ava2000** [comment]
Scenario 2: Create Cash Contra
Creation of GT Transaction
Select Bank
-Select PDSU
-Select Currency
-Key-IN Payee
-Cheque No.
Add Details
-Select Account
-Key-in Amount (Debit or Credit)
-Then click Save
-Message prompt "INTERNAL SERVER ERROR"
Result : NOT CORRECT
![image](https://user-images.githubusercontent.com/47963668/53470357-595bac00-3a9c-11e9-9356-1f7366cf939b.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9802

**Comment by jessa21** [comment]
OK
