### ISSUE TITLE
Procurement->Reporting->Purchase Analysis reports->Purchase Analysis -Supplier Wise - different fonts on the report.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#540]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/82f9f375-ff4b-4dd1-98f8-c36eae440c48)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/e80a6e75-242e-423b-a12e-9b5005873897)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13851**

**Comment by KatrinaCagaanan** [comment]
Resolved
