### ISSUE TITLE
Procurement->Reporting->Purchase Analysis reports->Purchase Analysis-Supplier by Group 12 months. Under Construction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#542]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/f932bd2b-2ee2-4baa-bcf7-752089b6baf0)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13863**

**Comment by KatrinaCagaanan** [comment]
Resolved
