### ISSUE TITLE
Procurement->Reporting->Purchase Analysis reports->Purchase analysis buyer wise. The total should be in 2 decimal places.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#543]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/80486a99-c11e-458b-be33-f32aafb0b903)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13860**

**Comment by KatrinaCagaanan** [comment]
Resolved
