### ISSUE TITLE
Procurement->Reports Queries->Reports & Queries->GRN Listing (tick detailed report). 1. Amounts should be in 2 decimal places. 2) Amount should be aligned on the proper columns

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#544]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/dd07c149-0a5c-4c20-92b7-bfae4e9aa486)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/f35be5b3-fd6c-4677-94f9-5eb9b22b060a)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13861**

**Comment by KatrinaCagaanan** [comment]
Resolved
