### ISSUE TITLE
Procurement->Reports Queries->Reports & Queries->GRN Listing. Account Group list empty.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#545]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/88060ead-d693-401f-9c86-29c43b2b8cfc)
There is a list of supplier account group:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/eb710055-a7b7-4d68-ab73-5807cfcc490c)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13853**

**Comment by KatrinaCagaanan** [comment]
Resolved
