### ISSUE TITLE
Procurement-> Order Processing->Supplier Bills->Invoice on PO. The PONO no is not being removed when I change the supplier.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#546]
Scenario:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/cea0a35a-6736-4c48-afa3-9dc3a956df28)
I then delete the line details so I can change the supplier name. There's the prompt that the PONO will be removed if I change the supplier:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/e23211ed-397f-4067-a710-540e08bccf99)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/8700c48f-59c2-4a36-aa66-e317dc8dc504).
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/3991b42e-fc0e-4a22-bd0c-9612d99f2fdf)

**Comment by ZawZawThein** [comment]
Changeset 13888

**Comment by KatrinaCagaanan** [comment]
Resolved
