### ISSUE TITLE
SALES->Order Processing->Operations->Goods Returned Credit Note (CC). Error prompt when editing CC.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#547]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/6536e6f9-f015-4464-bed2-8d48c001f385)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/0074a333-094b-410b-b72f-bc7549c941b8)

**Comment by ZawZawThein** [comment]
![Screenshot 2019-12-19 09 54 58](https://user-images.githubusercontent.com/47886841/71142557-1a266380-2246-11ea-8fd2-c1c07d72f3dd.png)

We should again publish with include this file.

**Comment by KatrinaCagaanan** [comment]
Resolved
