### ISSUE TITLE
SALES->Order Processing->Operations->Goods Returned Credit Note (CC). Cannot do allocation in CC.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#548]
1. Allocation by Allocation tab:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/296fbd02-78c6-4160-84f9-a1c0245d0cd5)

2. Allocation by batch Allocation:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/d569479e-71a4-4ad6-b7d6-99574ab3df09)

**Comment by ZawZawThein** [comment]
Changeset 13831

**Comment by KatrinaCagaanan** [comment]
Hi @ZawZawThein ,

I will re-open this ticket. I can select the transaction already, but when I click accept row , there's an error prompt.
![image](https://user-images.githubusercontent.com/47963355/71222286-f0834000-230a-11ea-96c4-6cdf11db605d.png)
![image](https://user-images.githubusercontent.com/47963355/71222314-14468600-230b-11ea-8673-3d2db09bbffe.png)

**Comment by KatrinaCagaanan** [comment]
Resolved
