### ISSUE TITLE
SALES->Order Processing->Operations->Goods Returned Credit Note (CC). Cannot call up ref trn type and transaction no when enter. Need to browse down and click.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#549]
In REF field, need to select from different transaction types.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/f4409b85-5440-40e7-8b40-2d8f2536ead6)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/92a112c8-c9ee-4976-93b0-b8d531586177)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/936705f6-8966-4981-82ff-c7049fb7c5ae)

**Comment by ZawZawThein** [comment]
Changeset 13827
Affected file: A21OPCreditNote_GetDataOptions.SQL

Changeset 13828

**Comment by KatrinaCagaanan** [comment]
Resolved
