### ISSUE TITLE
Cash Book -DRAFT CASH BANK APPROVAL . CANNOT DO APPROVAL

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#55]
Scenario 1: DRAFT CASH BANK TRANSACTION APPROVAL
No screen shown to approve the transaction
It only display the list of records created 
Result : NOT CORRECT
![image](https://user-images.githubusercontent.com/47963668/53550178-0acc1180-3b71-11e9-887b-8f6a9672c3ca.png)

**Comment by ZawZawThein** [comment]
Please go Draft Cash Book Transaction Pending for Approval page. This page can go approve or reject.
Finance > Cash Book > Operations > Draft Cash Book Transaction Approval
Link : ### http://a21.sg:94/CashBank/DraftQ21GLCashBankApproval/140

**Comment by jessa21** [comment]
OK to view GC > click on Approve or Reject button.
