### ISSUE TITLE
Procurement->Order Processing. The subtotal section should be in 2 decimal places. Please do for all transaction types.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#552]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/5629e029-42ed-4224-b8f5-079ad10cb550)

**Comment by zawuniqesolutions** [comment]
Waiting for publish.

**Changeset 13852**

**Comment by KatrinaCagaanan** [comment]
Resolved
