### ISSUE TITLE
FINANCE->Receivable->Reports->Reports&Queries->Customer Ledger. Tried to generate report for all customers but reports generated becomes blank/emtpy.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#555]
Tried to leave the customer field blank, meaning for all transactions but the report is empty.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/3be79762-3360-4ca8-b1d8-093d2fc4b6a7)
Tried to select all customer but also the same.
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/4390599a-1812-452e-a655-d78052824429)

**Comment by ZawZawThein** [comment]
Changeset 13874
fix using function [dbo].[R21ARLedger]: 
wrong code filter

**Comment by KatrinaCagaanan** [comment]
Resolved
