### ISSUE TITLE
Warehouse-STK Transaction-Stock Transaction (IT). After entering line type, the next line item automatically generates when accepting row. Need to delete the extra line item.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#556]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/7b0fed83-be67-4806-b138-a32cdd54b27a)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/34087906-1798-4284-af93-14f7bafc5b47)

**Comment by ZawZawThein** [comment]
Changeset 13875

**Comment by KatrinaCagaanan** [comment]
Resolved
