### ISSUE TITLE
SALES->Order Processing->Customer Sales Order-> Can still access the product master from sales transaction even though user settings set to untick "Allowed to access Product Master in sales/purchase tran." Please do for all transactions

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#557]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/12028444-3776-4f4d-9d14-ff9af67f504b)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/7a912534-7a23-486b-a62d-a01ccb2dd003)

**Comment by ZawZawThein** [comment]
Changeset: 14048

**Comment by KatrinaCagaanan** [comment]
Resolved
