### ISSUE TITLE
SALES->Order Processing->Goods Returned Credit Note (CC). Cost field  missing.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#558]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/c3c08848-154c-4ac4-86e4-0ece78e3c2ce)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/9737f57c-eb80-46b6-8009-b05c0cae6e8c)

![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/f840b984-33ec-4f95-963e-5635ebd6bc13)

**Comment by ZawZawThein** [comment]
Changeset 14053

**Comment by KatrinaCagaanan** [comment]
Resolved
