### ISSUE TITLE
Cash Book -DRAFT CASH BANK TRANSACTION POSTING. CANNOT DO POSTING

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#56]
Function: Cash Book -DRAFT CASH BANK TRANSACTION POSTING
Scenario 2: DRAFT CASH BANK TRANSACTION POSTING
No screen shown to approve the transaction
It only display the list of records created 
Result : NOT CORRECT
![image](https://user-images.githubusercontent.com/47963668/53550235-34853880-3b71-11e9-99a7-30204f4a44e4.png)

**Comment by ZawZawThein** [comment]
Please go this page Finance > Cash book > Draft Cash Bank Tran Posting >
and then view click.
Redirect page can post.

**Comment by jessa21** [comment]
Posting ok
