### ISSUE TITLE
Sales->Order Processing->Operations->Customer Sales Order(CO). Cannot create new transaction. Trnno becomes 0.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#561]
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/bd09f0e1-1054-4910-ba70-2954128d82ba)

**Comment by ykauniqe** [comment]
**IF EXISTS (SELECT name FROM sysobjects WHERE name = 'A21OPOrderHeaderTrnNoZeroUpdate')
   DROP TRIGGER A21OPOrderHeaderTrnNoZeroUpdate
GO

create TRIGGER A21OPOrderHeaderTrnNoZeroUpdate
ON A21OPOrderHeader
AFTER UPDATE, INSERT, DELETE
AS
BEGIN
    SET NOCOUNT ON;
	IF EXISTS( select * from A21OPOrderHeader where TrnNo = 0 ) 
BEGIN

alter table A21OPOrderDetail drop CONSTRAINT [FK_A21OPOrderDetail_A21OPOrderHeader] 

declare @LastNumberd int
select @LastNumberd = LastNumber+1 from U21TransactionNos where TrnType = 'CO'
Update A21OPOrderHeader set TrnNo = @LastNumberd where TrnType = 'CO' and TrnNo = 0
Update A21OPOrderDetail set TrnNo = @LastNumberd where TrnType = 'CO' and TrnNo = 0
Update U21TransactionNos set LastNumber = @LastNumberd where TrnType = 'CO'

ALTER TABLE [dbo].[A21OPOrderDetail]  WITH NOCHECK ADD  CONSTRAINT [FK_A21OPOrderDetail_A21OPOrderHeader] FOREIGN KEY([Company], [TrnType], [TrnNo])
REFERENCES [dbo].[A21OPOrderHeader] ([Company], [TrnType], [TrnNo])
NOT FOR REPLICATION 

ALTER TABLE [dbo].[A21OPOrderDetail] CHECK CONSTRAINT [FK_A21OPOrderDetail_A21OPOrderHeader]

end
    
END

GO






IF EXISTS (SELECT name FROM sysobjects WHERE name = 'A21OPOrderDetailTrnNoZeroUpdate')
   DROP TRIGGER A21OPOrderDetailTrnNoZeroUpdate
GO

create TRIGGER A21OPOrderDetailTrnNoZeroUpdate
ON A21OPOrderDetail
AFTER UPDATE, INSERT, DELETE
AS
BEGIN
    SET NOCOUNT ON;
	IF EXISTS( select * from A21OPOrderDetail where TrnNo = 0 ) 
BEGIN

alter table A21OPOrderDetail drop CONSTRAINT [FK_A21OPOrderDetail_A21OPOrderHeader] 

declare @LastNumberd int
select @LastNumberd = LastNumber+1 from U21TransactionNos where TrnType = 'CO'
Update A21OPOrderHeader set TrnNo = @LastNumberd where TrnType = 'CO' and TrnNo = 0
Update A21OPOrderDetail set TrnNo = @LastNumberd where TrnType = 'CO' and TrnNo = 0
Update U21TransactionNos set LastNumber = @LastNumberd where TrnType = 'CO'

ALTER TABLE [dbo].[A21OPOrderDetail]  WITH NOCHECK ADD  CONSTRAINT [FK_A21OPOrderDetail_A21OPOrderHeader] FOREIGN KEY([Company], [TrnType], [TrnNo])
REFERENCES [dbo].[A21OPOrderHeader] ([Company], [TrnType], [TrnNo])
NOT FOR REPLICATION 

ALTER TABLE [dbo].[A21OPOrderDetail] CHECK CONSTRAINT [FK_A21OPOrderDetail_A21OPOrderHeader]

end
    
END

GO**

**Comment by KatrinaCagaanan** [comment]
Resolved
