### ISSUE TITLE
Sales->Order Processing->Operations->Customer Sales Order(CO). Cannot change Currency and exchange rate in Sales Order even though settings is allowed to change currency and exchange rate.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#562]
Security settings is set to allow to change currency and exchange rate in sales order:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/ec952345-25e7-4f82-8fba-d8f441416bd9)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/3e4c7f0e-bd62-4df9-8a2c-5f8b443ca372)

**Comment by ZawZawThein** [comment]
Changeset 14062

**Comment by KatrinaCagaanan** [comment]
Resolved
