### ISSUE TITLE
SALES->Admin->Master Settings->Customer Maintenance->Price Tab. Can still see price table in customer settings even though settings is not allowed to access price table in customer master.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#563]
User maintenance settings is not allowed to access price table in Customer Master but when check customer, still can see price
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/e030bf5a-a804-472b-a809-5ae3c94e4118)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/a199c63e-456f-4850-a397-927ba144e1dc)

**Comment by ZawZawThein** [comment]
Changeset: 14057,14056,14055

**Comment by KatrinaCagaanan** [comment]
Resolved
