### ISSUE TITLE
Warehouse->Stk Transaction->Stock Transaction (IT). Transaction does not reflect in Stock Transaction Listing and GL Transaction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#564]
Created IT 92:
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/afec8670-3413-455f-8a86-af625ae453d2)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/265d88d6-bcae-4902-bf98-b8ce9f6f635d)
![image.png](https://images.zenhubusercontent.com/5cf8a04f2e4fe4691d7f073e/e0815f0a-de9e-4b40-9566-2284a1312f77)

**Comment by ykauniqe** [comment]
*** Remark pending for IT transaction duplicated stock item

**Comment by ava2000** [comment]
![image](https://user-images.githubusercontent.com/47963668/74503605-60d5c880-4f2c-11ea-9c56-6e7da74a6f59.png)

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/81917236-7e87fc00-9607-11ea-9d3b-921d0fd8cba3.png)

**Comment by jameslee888sg** [comment]
@zeusa2000  - is this same data showing a correct posting at the Clarity side?

**Comment by zeusa2000** [comment]
> @zeusa2000 - is this same data showing a correct posting at the Clarity side?

@jameslee888sg  Yes boss as per AYT need to create new Trn and the posting will be correct. Since this trn was created before the adjustment in the system.

**Comment by zeusa2000** [comment]
As per advise by AYT to create new trn and try to generate both reports Inventory and GL all are tied up.

![image](https://user-images.githubusercontent.com/51438852/82419704-5558e700-9ab1-11ea-9c18-884457164619.png)

![image](https://user-images.githubusercontent.com/51438852/82419728-5be75e80-9ab1-11ea-93cd-284c637b4cac.png)

**Comment by jameslee888sg** [comment]
@zeusa2000  - if we make a mistake at line level, how to delete that row to add another row? Pls verify this before closure.

**Comment by Aungyetun991990** [comment]
@jameslee888sg  as per @zeusa2000  Testing Transaction 92 has issue because  IT92 is old data  before we added logic (Allow duplicated Product in IT Transaction).So that Transaction IT92 Data is  only in IMD not in DraftIMD so that LineDetail in IT Screen can't able to show. But New IT Transaction has no issue.

**Comment by zeusa2000** [comment]
Boss @jameslee888sg can we close now this ticket? since @Aungyetun991990 explained above what happen on this ticket and as per my testing the issue has been fixed already.
