### ISSUE TITLE
Post Dated Cheque Mgmt 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#57]
Go Finance > Receivables > Post Dated Cheque
1 Add New Post Dated Cheque . Cheque = 5/3/2019  > Unposted Chq. 
System shown POSTED Date = 1/1/1990 

http://a21.sg:94/Receivables/PostD
![image](https://user-images.githubusercontent.com/47977411/53551421-3f8d9800-3b74-11e9-9f06-4029127d33a4.png)

2 - Post the chq 

system error occurs. 
![image](https://user-images.githubusercontent.com/47977411/53551679-c6db0b80-3b74-11e9-8dfc-7b6d88b64e01.png)

**Comment by ZawZawThein** [comment]
Changeset: 9828,9829

**Comment by ZawZawThein** [comment]
new Changeset: 9836
Affected file: PostDatedChequeController.cs

Changeset 9838
Affected File: PostDatedCheque_Content.cshtml

**Comment by jessa21** [comment]
Checked
