### ISSUE TITLE
Issue #4  Cannot preview the transaction. " There is no repx in the path"

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#574]
![image.png](https://images.zenhubusercontent.com/5e21742a52024f72e44b5940/7688a61e-bf6d-4558-95f7-4284c6e87dcf)

**Comment by Aungyetun991990** [comment]
There is no File in this location  your Repx name
You can map your repx in customized Report Document

**Comment by ava2000** [comment]
corrected in testing.
