### ISSUE TITLE
Receivables Report & Queries - Duplicated Menu 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#58]
http://a21.sg:94/Receivables/R21ARReports/50
http://a21.sg:94/Receivables/R21ARReports/1000

![image](https://user-images.githubusercontent.com/47977411/53551954-57b1e700-3b75-11e9-9ea0-5f78efbe32a9.png)

**Comment by ZawZawThein** [comment]
### Changeset: 9992
IF EXISTS ( Select 1 from u21menus where ItemName='R21ARReports' and ItemNumber=1000 )
	BEGIN
	     delete u21menus where ItemName='R21ARReports' and ItemNumber=1000 
	END
Go

**Comment by jessa21** [comment]
done
