### ISSUE TITLE
LY 4065 Finance>Receivable>Receivable Generator hit error 25 Feb 2019

### ISSUE THREAD

**Issue by LaiYingLeong** [a2000-erp-team/WEBERP#6]
![image](https://user-images.githubusercontent.com/47965549/53318638-ea9b1900-390a-11e9-9702-9218b42715a9.png)

**Comment by ZawZawThein** [comment]
It is new page, We have to create this page. Please hold on.

**Comment by ykauniqe** [comment]
yes, @LaiYingLeong , pls hold on this ticket just a while. let me ask @Than Than to develop. pls let you know after done.
