### ISSUE TITLE
Issue #5 When the user scrolls the data. Header should still appear

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#601]
![image.png](https://images.zenhubusercontent.com/5e21742a52024f72e44b5940/a7eee5de-40c0-4b03-931d-cb9e9bbbfaa5)

**Comment by roxannebernabe** [comment]
Hi R&D Team,
I tested this issue still persist. Please check again. Thanks

**Comment by roxannebernabe** [comment]
Closing this ticket. Issue already resolved.
