### ISSUE TITLE
ISSUE # 6 CANNOT SAVE THE IT TRANSACTION. ERROR MESSAGE APPEAR

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#602]
![image.png](https://images.zenhubusercontent.com/5e21742a52024f72e44b5940/6b7755c1-9e3f-4bfe-bc33-a2984b77063c)

**Comment by ava2000** [comment]
![image](https://user-images.githubusercontent.com/47963668/74397171-07e43280-4e4f-11ea-9bff-de6c7ecec2f9.png)

**Comment by roxannebernabe** [comment]
As per current testing. Issue Resolved. Closing this ticket.
