### ISSUE TITLE
ISSUE # 8 SYSTEM ALLOW TO DUPLICATE PRODUCT.THE FIRST PRODUCT ISSUE, THEN SAME PRODUCT RECEIVED. 

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#604]
![image.png](https://images.zenhubusercontent.com/5e21742a52024f72e44b5940/1e1d2ed3-084e-4cfb-ad3a-fcaf5eef0920)

**Comment by roxannebernabe** [comment]
As per current testing Issue resolved. CLosing this ticket.
