### ISSUE TITLE
Issue #10 User create an existing account. Error message should be descriptive

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#606]
![image.png](https://images.zenhubusercontent.com/5e21742a52024f72e44b5940/f4da83b0-8043-4449-8dad-d501cd9cec52)

**Comment by ava2000** [comment]
error message should be descriptive to the user.meaning the simple user can understand . Error message can be like "CANNOT SAVE AN EXISTING ACCOUNT!"

**Comment by roxannebernabe** [comment]
As per current testing. Issue Resolved. Closing this ticket.
