### ISSUE TITLE
Issue # 8 In Menu Maintenance, under Stock Transfer (Direct). The DESCRIPTION set to blank whenever the user edit this Menu.

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#609]
![image.png](https://images.zenhubusercontent.com/5e21742a52024f72e44b5940/8a23dff5-f9c7-41b0-b65b-e7825105df25)

**Comment by roxannebernabe** [comment]
Closing this Ticket Issue Resolved.
