### ISSUE TITLE
Issue #11 Wrong amount shown in the report Stock Transaction listing

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#612]
![image.png](https://images.zenhubusercontent.com/5e21742a52024f72e44b5940/f837bf67-3b5e-4b05-9db9-1dd3f98f97c9)
![image.png](https://images.zenhubusercontent.com/5e21742a52024f72e44b5940/d9f2850a-b09f-4a68-8856-871e14411b1c)

**Comment by roxannebernabe** [comment]
As per current Testing issue still persist. Re-open this ticket 612

**Comment by Aungyetun991990** [comment]
@roxannebernabe  Colud You Pls test with new IS Translation and test again on Stock Transaction Listing

**Comment by roxannebernabe** [comment]
I retested. Issue is resolved. Closing this ticket.
