### ISSUE TITLE
Issue #15 Add button does not appear. Even we set in the Menu Maintenance

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#616]
![image.png](https://images.zenhubusercontent.com/5e21742a52024f72e44b5940/6c056032-07d1-4735-bf1f-32e0c3175c89)
![image.png](https://images.zenhubusercontent.com/5e21742a52024f72e44b5940/b59e7d23-a3fb-4b4c-ba46-568e7ddeeb85)

**Comment by roxannebernabe** [comment]
As per current testing. Issue Resolved. Closing this ticket
