### ISSUE TITLE
Finance -> Ledger -> Reports ->Reports & Queries -> Transaction Listing

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#62]
Finance -> Ledger -> Reports ->Reports & Queries -> Transaction Listing

To check on GO 4 Transaction Listing report
![2019-02-28_17h27_09](https://user-images.githubusercontent.com/47963293/53555743-7e741b80-3b7d-11e9-8444-74c1fa9939a0.png)

The preview shows as
![2019-02-28_17h28_34](https://user-images.githubusercontent.com/47963293/53555844-b4190480-3b7d-11e9-9881-1ee5944f068c.png)

2 issues:
1. The Ex rate of 2.00 does not show
2. The Debit Base and Credit Base show zero
    Should be Retained Earnings    Debit Base   200.00
                     Water & Beverage    Credit Base               200.00

Here is the GO 4 screenshot
![2019-02-28_17h31_25](https://user-images.githubusercontent.com/47963293/53556026-09551600-3b7e-11e9-962b-e1cdfcb1cd05.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9842

**Comment by ErwinMetra** [comment]
Now ok.
![2019-03-15_16h46_50](https://user-images.githubusercontent.com/47963293/54419589-ccbf1800-4742-11e9-8ac3-2f27dfa4f926.png)
