### ISSUE TITLE
Issue #20 Cannot test the BARCODE PRINTING. When the user clicks the Item, nothing happens. Cannot click PREVIEW.

### ISSUE THREAD

**Issue by ava2000** [a2000-erp-team/WEBERP#621]
![image.png](https://images.zenhubusercontent.com/5e21742a52024f72e44b5940/e686cd6a-e787-44b2-9ef9-2486c1185d3e)

**Comment by roxannebernabe** [comment]
I tried retesting but issue still persist. Please help to recheck. Thanks

**Comment by Aungyetun991990** [comment]
@roxannebernabe  You need to Click First Next Button and them You can Click Preview Button

**Comment by roxannebernabe** [comment]
As per current testing issue already resolved. Closing this ticket.
