### ISSUE TITLE
Finance -> Ledger -> Operations -> Enter GL Opening Balance (Exchange Rate prompt message)

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#63]
Finance -> Ledger -> Operations -> Enter GL Opening Balance (Exchange Rate prompt message)

Here is the prompt message when I choose a currency that is not a base currency.
![2019-02-28_17h16_20](https://user-images.githubusercontent.com/47963293/53556360-9c8e4b80-3b7e-11e9-96ea-fff43467ca84.png)

It should be OK instead of Yes.
It should be Cancel instead of No.

**Comment by zawuniqesolutions** [comment]
Changeset 9835

**Comment by ErwinMetra** [comment]
Perfect!
![2019-03-18_15h12_17](https://user-images.githubusercontent.com/47963293/54512791-49930180-4990-11e9-8417-1a6e2453f0d1.png)
