### ISSUE TITLE
Finance -> Ledger -> Operations -> Journal Voucher (ease of data entry, not using the TAB but using mouse)

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#64]
Finance -> Ledger -> Operations -> Journal Voucher (ease of data entry, not using the TAB but using mouse)

When inserting a new line detail in GJ, the user needs to click on the **+Detail** button
![2019-03-01_10h37_26](https://user-images.githubusercontent.com/47963293/53612610-11f52d00-3c0e-11e9-823a-1a1f6cbd3029.png)

After completing the details in this new line, the user needs to click on the check button
![2019-03-01_10h43_49](https://user-images.githubusercontent.com/47963293/53612652-44068f00-3c0e-11e9-8ae0-a7debcf682f8.png)

For ease of data entry, after clicking this check button, can we open up a new line detail so no need for the user to click the **+Detail** button again to insert a new line?

If the user will not use this new line to insert, can the user click ESC button from keyboard? or click on the X button?

**Comment by zawuniqesolutions** [comment]
Already covered in latest code.
Please test again @ErwinMetra

**Comment by jessa21** [comment]
same with #18 
press ESC, ESC button , it won't go to Preview button...  
accept row - it won't open a new line detail

**Comment by ZawZawThein** [comment]
### Changeset 10216
Affected file:  GeneralLedger\Views\A21GLTransaction\A21GLTransaction_Script.cshtml

**Comment by zeusa2000** [comment]
As per testing automatically add a new line after click the accept row and can preview now the report.

![image](https://user-images.githubusercontent.com/51438852/62912270-06f81880-bdba-11e9-87c5-33770ebf55e6.png)

![image](https://user-images.githubusercontent.com/51438852/62912285-18d9bb80-bdba-11e9-8f9c-c01949be0f3d.png)
