### ISSUE TITLE
Home -> System Manager -> Transactions -> Select Customized Documents

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#65]
Home -> System Manager -> Transactions -> Select Customized Documents

When I click on red X button, there is a prompt message showing **Error Report Data do not have**
![2019-03-01_11h10_07](https://user-images.githubusercontent.com/47963293/53613804-34894500-3c12-11e9-8ba4-9a4e6d7ac6e8.png)

Can we just take this X button because the user just need to choose the repx file to map. The user is not supposed to delete the line because it is a default 8 line of designs.

**Comment by zawuniqesolutions** [comment]
Changeset 9832

**Comment by ErwinMetra** [comment]
Now, it is cleaner, the x button has now been removed.
