### ISSUE TITLE
TestWeb1 [maria]- In Cash Book, operations, draft GC , cannot add entry

### ISSUE THREAD

**Issue by maria2k** [a2000-erp-team/WEBERP#657]
Testing Web1- In Cash Book, operations, draft GC , cannot add entry
[After header, when add ‘detail’ , it show warning sign to select trntype , TRN no and record no.}
![image](https://user-images.githubusercontent.com/63994238/80162013-b1406500-8604-11ea-8e12-13b028a63c43.png)

**Comment by maria2k** [comment]
![image](https://user-images.githubusercontent.com/63994238/82548873-9e329d80-9b8e-11ea-94b5-b1a91eb267f5.png)
In Cash book, GC draft, add, header-prompt exchange rate,when select 'cancel' or 'ok',  cannot process.

**Comment by maria2k** [comment]
![image](https://user-images.githubusercontent.com/63994238/83231142-98a40b80-a1bd-11ea-8056-05758f5c9da4.png)
1Concern-cannot edit previous line transaction
2tested on Add & Remove- ok.

**Comment by maria2k** [comment]
![image](https://user-images.githubusercontent.com/63994238/83231205-b5d8da00-a1bd-11ea-8ce7-178a368a7e45.png)
3 After save, then retrieve GC3, can edit. Suggestion-can we edit while inside the form.

**Comment by myothuaung46** [comment]
> ![image](https://user-images.githubusercontent.com/63994238/83231142-98a40b80-a1bd-11ea-8056-05758f5c9da4.png)
> 1Concern-cannot edit previous line transaction
> 2tested on Add & Remove- ok.

You can't select Account so you can see above message.

**Comment by maria2k** [comment]
tested ok.
