### ISSUE TITLE
Finance -> Ledger -> Operations -> Journal Voucher (Preview Report issue)

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#66]
Finance -> Ledger -> Operations -> Journal Voucher (Preview Report issue)

When i want to preview GJ 407 and selected the 1st repx format, there is a preview issue
![2019-03-01_11h29_51](https://user-images.githubusercontent.com/47963293/53614443-fe00f980-3c14-11e9-9b03-c155a539b9ca.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9837

**Comment by ErwinMetra** [comment]
Now, can preview, no error message.
