### ISSUE TITLE
Finance -> Ledger -> Operations -> Journal Voucher (using TAB, after Date field issue)

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#67]
Finance -> Ledger -> Operations -> Journal Voucher (using TAB, after Date field issue)

There is no auto-number
When I create a new GJ, the cursor is defaulted in the Ref No field,
then I clicked on the TAB button, the cursor went to the Date (which is perfect)
but when I changed the date and clicked on the TAB button, the cursor went somewhere 

By right, the cursor should point to the next field which is Project.

![2019-03-01_11h43_29](https://user-images.githubusercontent.com/47963293/53615451-e166c080-3c18-11e9-8986-b130565ef26d.png)

**Comment by zawuniqesolutions** [comment]
It's is already fixed and working in published site too.
Please check again @ErwinMetra
