### ISSUE TITLE
LY 4131 Finance>Cash Bank>Draft Cash Bank Transaction Approval

### ISSUE THREAD

**Issue by LaiYingLeong** [a2000-erp-team/WEBERP#68]

**Comment by LaiYingLeong** [comment]
![image](https://user-images.githubusercontent.com/47965549/53615515-330f4b00-3c19-11e9-9139-38bdaf9fdd6f.png)

**Comment by LaiYingLeong** [comment]
Amount is wrong, Missing header and view button cannot click

**Comment by zawuniqesolutions** [comment]
Changeset 9823

**Comment by zawuniqesolutions** [comment]
Hi @LaiYingLeong 
For nothing happen when you click 'View' button, you need to allow popup in your browser.
Check how to do it - https://www.asus.com/us/support/FAQ/1007483/
P.S - if you are not using Chrome, you can reference for other browsers.

For 'Amount' not equal, that is not the same showed value for Approval and Draft.
'Amount' for Approval => use 'BillAmount'
'Amount' for Draft => use 'Amt'.
Please check with Clarity.
