### ISSUE TITLE
LY 4131 Finance>Receivable>Reports>Credit Control Approval

### ISSUE THREAD

**Issue by LaiYingLeong** [a2000-erp-team/WEBERP#69]
![image](https://user-images.githubusercontent.com/47965549/53615685-19223800-3c1a-11e9-84ba-13ac24270ab3.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9821

**Comment by jessa21** [comment]
Credit Control Approval is a customization module. It already hide from menu now. 
it is pending for enhancement in phase 2.
