### ISSUE TITLE
LY 4065  Finance>Receivable>Operations>Batch Invoice Allocation

### ISSUE THREAD

**Issue by LaiYingLeong** [a2000-erp-team/WEBERP#7]
Finance>Receivable>Operations>Batch Invoice Allocation-need to default the correct currency
![image](https://user-images.githubusercontent.com/47965549/53318791-5c736280-390b-11e9-9a89-3d11fbe63097.png)
![image](https://user-images.githubusercontent.com/47965549/53318798-6301da00-390b-11e9-9f4d-a4df3370ef59.png)

**Comment by ZawZawThein** [comment]
Changeset: 9799

**Comment by jessa21** [comment]
OK . Select Bank SGD > Currency = SGD.
