### ISSUE TITLE
Search Function -  Account Name 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#71]
I enter 00002000, 5009000, 00003000 , system will not able to search the Account Number > select > No records. 

I enter Acc Name = Sales ADJ > select Sales ADJ > system won't display the account name in column. 

http://a21.sg:94/GeneralLedger/R21GLReports/1000
![image](https://user-images.githubusercontent.com/47977411/53781894-bc8a8a00-3f45-11e9-9ac2-e4023d02d265.png)

**Comment by zawuniqesolutions** [comment]
Please test again in testing site.
if you still have this issue, let me know with more clarifications about it.

**Comment by jessa21** [comment]
Checked .
