### ISSUE TITLE
AR Report & Queries - Date From and Date To are mandatory for AR Statement of Acc  

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#72]
how to set Date From & Date To? 
We set Age on Date when filter SOA rpt in Clarity . System pick up the transaction period of the particular month. 

http://a21.sg:94/Receivables/R21ARReports/50#collapse1_Reports
![image](https://user-images.githubusercontent.com/47977411/53786890-07ad9880-3f58-11e9-8f71-4b8173165d4d.png)

2 - AR Statement of Account (Periodic), group by currency under construction. 
http://a21.sg:94/Receivables/R21ARReports/50#collapse1_Reports

**Comment by ZawZawThein** [comment]
Issues 1: Please test again. This message does not show.
Issues 2: The report also doesn't have Clarity version. Can we skip this issue?

**Comment by jessa21** [comment]
@ZawZawThein  
Pls verify 
http://a21.sg:94/Receivables/R21ARReports/50#collapse1_Reports
![image](https://user-images.githubusercontent.com/47977411/54007707-08377080-419e-11e9-9ead-edea86fae3c7.png)

**Comment by ZawZawThein** [comment]
![72](https://user-images.githubusercontent.com/47886841/54503793-3451af00-495f-11e9-804e-44d0ca27ae7a.png)

Please try again this page.

**Comment by jessa21** [comment]
checked.

**Comment by jessa21** [comment]
@ZawZawThein  - server error is solved. 

I checked on Age on Date for AR Aging Analysis , the same message " Date From Date To Date are mandatory " . 

http://a21.sg:94/Receivables/R21ARReports/50#collapse1_Reports

![image](https://user-images.githubusercontent.com/47977411/54588513-3189b380-4a5e-11e9-989e-e055b221ccdd.png)

The validation message is same as AR Statement of Acc as above mentioned.

**Comment by ZawZawThein** [comment]
### Please Go Finance > Receivables > Reports & Queries >
It is link **http://a21.sg:94/Receivables/R21ARReports/50**.
Please use this link instead of using 
**http://a21.sg:94/Receivables/R21ARReports/50#collapse1_Reports**

**Comment by jessa21** [comment]
Done
