### ISSUE TITLE
Procurement> Purchase Operations>Supplier Product Period Pricing Listing

### ISSUE THREAD

**Issue by LaiYingLeong** [a2000-erp-team/WEBERP#73]
Procurement> Purchase Operations>Supplier Product Period Pricing Listing
To display the name of customer and not the customer code and also why the Supplier Name is grey off ?  Clarity can filter by both code and name see image

![image](https://user-images.githubusercontent.com/47965549/53929122-a73d6900-40c7-11e9-8c3e-35df30b3313e.png)
![image](https://user-images.githubusercontent.com/47965549/53929137-b1f7fe00-40c7-11e9-8ef3-596e73bca950.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9881

**Comment by zawuniqesolutions** [comment]
Changeset 9895

**Comment by jessa21** [comment]
Supplier Name displayed.
