### ISSUE TITLE
Procurement>Billings>Invoice on PO

### ISSUE THREAD

**Issue by LaiYingLeong** [a2000-erp-team/WEBERP#75]
How to delete detail line of the SE?
![image](https://user-images.githubusercontent.com/47965549/53930425-2d5bae80-40cc-11e9-9b38-bb8f23c4eff1.png)
![image](https://user-images.githubusercontent.com/47965549/53930434-364c8000-40cc-11e9-93cc-df9218b54597.png)

**Comment by ZawZawThein** [comment]
![75](https://user-images.githubusercontent.com/47886841/54006125-71ad8400-418a-11e9-8a76-178d2774d317.png)

### Changeset 9873
**Please double click line detail. It can delete row. Thanks**
