### ISSUE TITLE
Missing EDIT Button in GL transaction

### ISSUE THREAD

**Issue by A2000-ISTEAM** [a2000-erp-team/WEBERP#750]
FINANCE - LEDGER - GL OPERATION - ADD [Journal Vouchers]

![image](https://user-images.githubusercontent.com/62376141/82478955-464f5480-9b04-11ea-8983-95bd1f1add4d.png)

**Comment by Aungyetun991990** [comment]
Edit Button is not available in Web Version But You Can Search Data by Keep in Trn No. 
If you want to see transaction , you need to exit first
