### ISSUE TITLE
Sales=>Sales Operations=>Sales Order

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#757]
Cannot select any GST type all are default as 7%.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/8b93e2f2-44b2-431d-9734-94b7e3efa9a1)

**Comment by EiEiZin** [comment]
@zeusa2000 , i can't simulate this issue. can you provide the way how can i simulate to get this error ? 

![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/c0fce5a9-a064-4d9d-9670-6a29ee7416d9)

**Comment by zeusa2000** [comment]
Hi @EiEiZin , Please see the wetransfer attachment sample video. Those stock item is not an serialized item. Please try to create a new line detail.

Please check this video link ===>>>> https://we.tl/t-jcGOeqGxNX

**Comment by EiEiZin** [comment]
@zeusa2000 ,  there's user setting to enable /disable the GST section. this condition is checking when adding line detail, need we check when editing. I've fixed for it. pls check.

![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/dffc7287-bdc1-4808-b46a-145ca09df7d6)

For "Please enter numeric value only for Serial No." message,  I've already fixed int ticket no #777.

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/82974204-fe509600-a00b-11ea-8578-a88f59f58a3a.png)

Thanks @EiEiZin didn't notice this user control access. Issue solved.
