### ISSUE TITLE
Procurement>Purchase Requsistion New Exchange Rate not defaulted

### ISSUE THREAD

**Issue by LaiYingLeong** [a2000-erp-team/WEBERP#76]
New did not default exchange rate.  Clone also did not default exchange rate 
![image](https://user-images.githubusercontent.com/47965549/54001678-1ded6b80-4187-11e9-9b8b-a5342d95ed37.png)
Clone without attachment and click Save Draft cannot save as draft
![image](https://user-images.githubusercontent.com/47965549/54002730-973a8d80-418a-11e9-88b9-e8cc87e8fc3f.png)

**Comment by zawuniqesolutions** [comment]
1) Please define Base Currency
![image](https://user-images.githubusercontent.com/47886892/54195481-2a5a2700-44ed-11e9-8704-7d6488ea142b.png)

2) Please define Default Exchange Rate
![image](https://user-images.githubusercontent.com/47886892/54195527-4e1d6d00-44ed-11e9-884a-29ee7e69d373.png)

That will be solved.

**Comment by zawuniqesolutions** [comment]
Changeset 9902

**Comment by jessa21** [comment]
ok
