### ISSUE TITLE
Sales=>Sales Operation=>Contact and Remarks not reflected on REPX

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#767]
CO 363 tried to resave the trn and the details still not reflected on the REPX.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/68a72da5-414a-402e-8656-c32d57a2da54)

**Comment by EiEiZin** [comment]
@zeusa2000 , the Report gets Customer Master's Contact for Contact Person 
And gets below marked Narration data for Other Sales Order Information.

![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/f21667ee-7b80-43e9-a029-44c9d8a15b53)

![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/7d32399e-df70-4128-be20-8b1699bfcb95)

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/82996318-581a8580-a037-11ea-8e29-f416fe99a82a.png)

Noted on the contact person under master customer details.
Notice that when I enter on the narration under additional detail its need to save the trn before you can preview. When you save you need to search again the transaction.

Please change the font style of description and

**Comment by zeusa2000** [comment]
Hi @EiEiZin the font is fixed but I have concern on the previewing of repx when you update something on the transaction and you want to preview the template, you cannot see the updated data you need to re-save and requery the transaction it took a long time for the user to see the updated data. On the clarity once you update any line details automatic save and reflect into repx. Please see this video.

https://we.tl/t-XF04kY0LrY

**Comment by EiEiZin** [comment]
@zeusa2000 , In Web ERP, need to click save button to save the transaction, not save/update automatically.

**Comment by zeusa2000** [comment]
Noted. Can close now this ticket. Thanks @EiEiZin
