### ISSUE TITLE
Procurement>Purchase Requisition Approval

### ISSUE THREAD

**Issue by LaiYingLeong** [a2000-erp-team/WEBERP#77]
Login as Robyn key in PR28 and PR29 which are submitted to Raja for approval.
Login as Raja there is no record shown for approval
![image](https://user-images.githubusercontent.com/47965549/54004250-e0d9a700-418f-11e9-83e5-0ca0071797b8.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9942

**Comment by jessa21** [comment]
@LaiYingLeong 

Login as "Raja" and can view applicant . 

![image](https://user-images.githubusercontent.com/47977411/56013614-3b809880-5d24-11e9-886a-f30c10159f08.png)

![image](https://user-images.githubusercontent.com/47977411/56013627-49361e00-5d24-11e9-9915-c0aeca03f9fa.png)
