### ISSUE TITLE
Procurement>Approval History Empty

### ISSUE THREAD

**Issue by LaiYingLeong** [a2000-erp-team/WEBERP#78]
PR 27 is approved by Robyn.  Login using Robyn Go to Approve PR tab and Click on Approval History it is empty.  There should be record like PR27 in the history
![image](https://user-images.githubusercontent.com/47965549/54012131-0b3b5c80-41b0-11e9-8dff-6a65190361ad.png)
No record in Robyn Approval History
![image](https://user-images.githubusercontent.com/47965549/54012229-63725e80-41b0-11e9-9b19-e4361b06af1f.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9905
