### ISSUE TITLE
Sales=>Sales Operations=>CO Missing Section and Unit under PDSU.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#785]
Missing section and unit under PDSU as per checking the Section and Unit is intact.

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/12c31cb2-b513-456a-8dda-641abc7f19d6)

![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/0a91b3e8-fa4a-457c-98d6-1cb579c6715f)

**Comment by EiEiZin** [comment]
@zeusa2000 , To show/hide and default value for these fields, there's form setting as below.

![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/faa71743-67c3-4ddc-8f67-4f682fbf944d)

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/82975803-0ca0b100-a010-11ea-9718-08e9b484843a.png)

Issue Solved, and noted additional knowledge to be set up on WebERP since the clarity fixed to show always the PDSU. Thanks @EiEiZin
