### ISSUE TITLE
Finance>Cash Bank>Operations>InterBank Giro Transaction Status

### ISSUE THREAD

**Issue by LaiYingLeong** [a2000-erp-team/WEBERP#79]
![image](https://user-images.githubusercontent.com/47965549/54099496-99078980-43f4-11e9-9684-8f755490463c.png)
![image](https://user-images.githubusercontent.com/47965549/54099506-a290f180-43f4-11e9-9b7a-236c6ee9a2e3.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9911

**Comment by jessa21** [comment]
@zawuniqesolutions  same error happens 
http://a21.sg:94/CashBank/frmIBGReadFateFile/100
![image](https://user-images.githubusercontent.com/47977411/56117094-f49bd880-5f99-11e9-8702-9e7b343e80da.png)

**Comment by zawuniqesolutions** [comment]
Changeset 10494

**Comment by zeusa2000** [comment]
As per testing the module is working propely.

![image](https://user-images.githubusercontent.com/51438852/59578089-27c52a00-90f9-11e9-8c18-aec09ba8da63.png)
