### ISSUE TITLE
JO-3965 Ledger-> Reports and Queries -> GST Report -> GST Form 5 Statement (By GST Type). The report is blank.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#80]
![image](https://user-images.githubusercontent.com/47963355/54104136-bb57d200-4409-11e9-9134-fba5e6745e50.png)

**Comment by ZawZawThein** [comment]
![14 3 2019](https://user-images.githubusercontent.com/47886841/54337634-e33f7380-465d-11e9-8ad1-b5dba6d4e836.png)

Please try again. I think , It should be select date range if the data exit.

**Comment by jessa21** [comment]
GST report can be viewed with data exist. 
if no data, blank value will be displayed in column

**Comment by jessa21** [comment]
Checked
