### ISSUE TITLE
JO-3965 Ledger-> Reports and Queries -> GST Report -> GST Form 5 Statement (Foreign Based) is Under Construction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#81]
![image](https://user-images.githubusercontent.com/47963355/54104203-ecd09d80-4409-11e9-9484-b84469dd1c0a.png)

**Comment by zawuniqesolutions** [comment]
This is already fined.
Check again please.

![image](https://user-images.githubusercontent.com/47886892/54266105-2093fa80-45a5-11e9-8726-f232c93c3f5d.png)
