### ISSUE TITLE
PROC-PURC-SUPPBILLS-Purchase Return-[Error for item _Oyster_Test2: Quantity More than Stock Available]

### ISSUE THREAD

**Issue by roxannebernabe** [a2000-erp-team/WEBERP#810]
![image.png](https://images.zenhubusercontent.com/5e8ee3dc283f36435d71984d/c6cf81bf-abe0-43eb-8f62-71a9987206a3)

![image.png](https://images.zenhubusercontent.com/5e8ee3dc283f36435d71984d/bb40697f-3675-42c3-88a0-7f79a524c76e)

**Comment by EiEiZin** [comment]
@roxannebernabe , There's lot Item Stock for this lot Item product and you selected Warehouse - WH. so you need to select the lot ID from Lot Item Stock as below and test again. 


![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/acbfd046-37cb-448a-8f6c-64412a5ac12d)

![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/5ac58e22-2014-4cff-8c63-5b588b077d49)

**Comment by roxannebernabe** [comment]
Noted @EiEiZin  closing this issue.
