### ISSUE TITLE
Sales=>SalesOperation=>CY Repx Line details not reflected.

### ISSUE THREAD

**Issue by zeusa2000** [a2000-erp-team/WEBERP#811]
![image.png](https://images.zenhubusercontent.com/5cfdcdd5171db04ec3637a3b/2b5b324a-029a-4dff-9578-fbdc6789be5b)

**Comment by zeusa2000** [comment]
![image](https://user-images.githubusercontent.com/51438852/83595581-09b83a00-a595-11ea-8dd2-51e4521706e8.png)

There still a false message.

**Comment by EiEiZin** [comment]
@zeusa2000 , it's  Item Memo value.

![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/4a8b6399-413e-4339-94c1-5f44e838875d)

**Comment by zeusa2000** [comment]
Noted @EiEiZin but I think there is a problem on item memo I never input false message please see this video capture it came out whenever you create additional line item.

https://we.tl/t-C3fy94Fvmr

**Comment by zeusa2000** [comment]
Bug on false message disappear, Issue fixed.

![image](https://user-images.githubusercontent.com/51438852/85675682-85228c80-b6f8-11ea-815b-0d4be0c5348b.png)

Template seems okay.

![image](https://user-images.githubusercontent.com/51438852/85675796-99ff2000-b6f8-11ea-8c82-5977ad889b80.png)
