### ISSUE TITLE
Enhancement for Finance Dashboard (Total Assets, ...)

### ISSUE THREAD

**Issue by A2000-ISTEAM** [a2000-erp-team/WEBERP#817]
FINANCE-DASHBOARD-FINANCEDASHBOARD(TOTAL ASSETS,....)

![image.png](https://images.zenhubusercontent.com/5e8e8265b7c1d9906c2bbc2c/19bb5975-c7c9-4f05-bff5-241b8ace9c81)

**Comment by EiEiZin** [comment]
@ABIGAIL,these percentage calculate based on total amount. 
i've updated it to show total amount too. (fig 1) 

to put the year eg ( Year 2020), if you filter the dashboard with parameter eg ( from 2019/01/01 to 2019/12/31), the figure shows for this date range. if so.. title will not be matched with the figure. 
 
fig 1) 
![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/d0c640d4-ebae-4a17-8e40-ac81bad827e5)

**Comment by A2000-ISTEAM** [comment]
@EiEiZin 
please put Year eg 2020; Qtr eg Q1 to Q3; Mth eg April 2020

the period are very important information to users

**Comment by A2000-ISTEAM** [comment]
Will close this case first till have a better idea how to do this dashboard.
