### ISSUE TITLE
PROC-PURC-SUPPBILLS-GRN on Order-[Unable to delete line item and clear reference SO]

### ISSUE THREAD

**Issue by roxannebernabe** [a2000-erp-team/WEBERP#818]
![image.png](https://images.zenhubusercontent.com/5e8ee3dc283f36435d71984d/4fb7d238-aeb6-4e62-9ae5-1bf7c2ebe3ef)

**Comment by roxannebernabe** [comment]
not yet resolved as per checking unable to remove reference SO still.

**Comment by EiEiZin** [comment]
@roxannebernabe , 
i checked with user - Roxanne, it can be removed 

![1.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/4e57e470-c44c-4a13-b1e2-da4f564e7bb5)

**Comment by roxannebernabe** [comment]
Closing this ticket. Already resolved.
