### ISSUE TITLE
JO-3965  Ledger-> Reports and Queries -> GST Report -> GST Refund. Under construction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#86]
![image](https://user-images.githubusercontent.com/47963355/54104374-8c8e2b80-440a-11e9-9977-c24e3d75ed97.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9921

**Comment by jessa21** [comment]
able to view GST Refund Listing
