### ISSUE TITLE
PROC-PURC-REPORTS&QUERIES-Master Listing-[Query button is disabled]

### ISSUE THREAD

**Issue by roxannebernabe** [a2000-erp-team/WEBERP#861]
Kindly check all reports in Reports and queries whythe Query Button is disabled?

![image.png](https://images.zenhubusercontent.com/5e8ee3dc283f36435d71984d/d57c5c83-51a7-4114-8927-5661c7811253)

**Comment by AungKo2019** [comment]
MSTSupplier
AROutstanding
GLLedger
GLTrialBalanceDate
GLUnbalanced

only these 5 report can access the Query Button.
Other reports can't access .

**Comment by roxannebernabe** [comment]
Noted. Thanks Closing this ticket.
