### ISSUE TITLE
JO-3965 Ledger-> Reports and Queries -> GST Report -> GST Grouping Listing (foreign Based by GST Type). Under construction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#87]
![image](https://user-images.githubusercontent.com/47963355/54104399-ae87ae00-440a-11e9-90c0-38a76682df84.png)

**Comment by ZawZawThein** [comment]
Changeset 9909
Changeset 9910
Changeset 9912
Changeset 9913
Changeset 9914

**Comment by jessa21** [comment]
Preview OK
