### ISSUE TITLE
Receivables Report & Queries 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#88]
Report under construction 
http://a21.sg:94/Receivables/R21ARReports/1000
1 - Receivable by Project Analysis  http://a21.sg:94/Receivables/R21ARReports/1000
2 - Revaluation Outstanding 
3 - AR Service Invoice Listing 
4 - AR Outstanding Statement 
5 - AR Outstanding Statement with Credit Terms 

6 -Aging Analysis on Forex - If tick Detail Report > System will not displayed the rpt > Blank Page 
 http://a21.sg:94/Receivables/R21ARReports/50
![image](https://user-images.githubusercontent.com/47977411/54110515-8ef98100-441c-11e9-8577-8b940bd661a7.png)

7

**Comment by zawuniqesolutions** [comment]
1) Changeset 9926
2) Changeset 9930
4) Changeset 9931

**Comment by zawuniqesolutions** [comment]
@jessa21 
For 6, there is nothing issues about report.
Problem is there is hue amount of record to show report.
So, next time you test with some filter value like customer or currency or something.

![image](https://user-images.githubusercontent.com/47886892/54406707-7ed9ee00-4709-11e9-860e-33fe63adfc45.png)

**Comment by jessa21** [comment]
it takes time to load SOA report. 
click Preview > takes 8 min to preview 26 SOA rpts.

**Comment by zawuniqesolutions** [comment]
Changeset 9971
Changeset 9972

**Comment by jessa21** [comment]
Done
