### ISSUE TITLE
Credit Control Approval 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#89]
Credit Control Approval is a customised module, it is not a standard module in Clarity. 
We may remove / hide it in ERP Web. Will confirm with @jameslee888sg James. 

Error occurs when open http://a21.sg:94/Receivables/CreditControlApproval/210
![image](https://user-images.githubusercontent.com/47977411/54111874-e2210300-441f-11e9-9d34-47ad58f5cef4.png)

Clarity > Credit Control Approval
![image](https://user-images.githubusercontent.com/47977411/54114035-7beaaf00-4424-11e9-85b4-8442c109b45d.png)

**Comment by ZawZawThein** [comment]
We hide Credit Control Approval tab just a while.  
### Changeset: 9908
Affected file: License.txt

**Comment by jessa21** [comment]
@ZawZawThein  I checked http://a21.sg:94/Receivables/CreditControlApproval/210 
same error occurs when click Credit Control Approval . I pressed CTRL & F5 too.

**Comment by jessa21** [comment]
Enhancement is required in Phase 2. To be advised.
