### ISSUE TITLE
Send Statement of Account 

### ISSUE THREAD

**Issue by jessa21** [a2000-erp-team/WEBERP#90]
Error when open http://a21.sg:94/Receivables/SendStatementOfAccount/180

![image](https://user-images.githubusercontent.com/47977411/54112004-2d3b1600-4420-11e9-8cfd-96647090dab4.png)

**Comment by ZawZawThein** [comment]
Please include all these file under in 
**Areas\Receivables\Views\SendStatementOfAccount
Model:  Areas\Receivables\Models\SendStatementOfAccountModel.cs
Controller:  Areas\Receivables\Controllers\SendStatementOfAccountController.cs
Dataset: Report_Dataset\EStatementOfAccount\EStatementOfAccount.xsd**


New Changeset: 9903
