### ISSUE TITLE
Finance -> Ledger -> Operations -> Enter GL Opening Balance (PREVIEW)

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#92]
Finance -> Ledger -> Operations -> Enter GL Opening Balance (PREVIEW)
Request: Change the header to **GL Opening Balance** instead of **Journal Voucher**
![2019-03-18_15h25_20](https://user-images.githubusercontent.com/47963293/54513453-72b49180-4992-11e9-847a-b99713df2239.png)

**Comment by AungKo2019** [comment]
**###  Changeset  No :10070**

**Comment by zeusa2000** [comment]
As per testing the header is now correct into GL Opening balance.

![image](https://user-images.githubusercontent.com/51438852/62911491-22adef80-bdb7-11e9-8ab0-157ac1f2c8c5.png)
