### ISSUE TITLE
FINANCE – PAYABLES – PAYMENT TRANSACTION (AP) – TRANSACTION LISTING

### ISSUE THREAD

**Issue by A2000-ISTEAM** [a2000-erp-team/WEBERP#924]
Supplier Invoice in USD, Payment from SGD Bank Account with Exchange differences

![2020-06-17_12h26_29.png](https://images.zenhubusercontent.com/5e8e8265b7c1d9906c2bbc2c/ddca2e91-50d4-449a-b96a-d504cfdec24a)

![2020-06-17_12h26_51.png](https://images.zenhubusercontent.com/5e8e8265b7c1d9906c2bbc2c/4532801c-5363-40cd-b2b6-ec13a2afb4ae)

Short of one Trade Creditor A/C of 214 and 287.53, both Debit Amount

**Comment by Aungyetun991990** [comment]
hello @RIchard
 After I check on 94 site  there is no issue so Could you pls show me how did you enter PV transaction.
![image.png](https://images.zenhubusercontent.com/5c7375dc80b66c1936f9fc1f/27d085e9-98e3-43d1-bbf3-576a66f7e0d9)
