### ISSUE TITLE
Finance -> Ledger -> Operations -> Journal Voucher (PREVIEW)

### ISSUE THREAD

**Issue by ErwinMetra** [a2000-erp-team/WEBERP#93]
Finance -> Ledger -> Operations -> Journal Voucher (PREVIEW)
1. There is only one line detail showing in the preview.
2. Also, the chart of accounts in the line detail is not showing.
![2019-03-18_15h10_46](https://user-images.githubusercontent.com/47963293/54521470-f3c95400-49a5-11e9-817d-c448aa5ac6c3.png)

**Comment by zawuniqesolutions** [comment]
Changeset 9973
Changeset 9981

**Comment by zeusa2000** [comment]
As per testing all the details is showing now.

![image](https://user-images.githubusercontent.com/51438852/59584424-92ce2b00-9110-11e9-958d-2685f7d44251.png)
