### ISSUE TITLE
Ledger-> Reports and Queries -> General Ledger-> General Ledger Listing (Multi Currency). Under Construction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#97]
![image](https://user-images.githubusercontent.com/47963355/54662455-09ab5600-4b19-11e9-8b36-a820d6d69530.png)

**Comment by ZawZawThein** [comment]
**Changeset 9996
Changeset 9997
Changeset 9998,10003**

Add: **GLLedgerMultiCur.cs
Repx: GLLedgerMultiCur.repx
Controller: R21GLReportsController.cs
Dataset: R21GLLedgerDataSet.xsd**

**Comment by zeusa2000** [comment]
Can preview now the report under general ledger listing. But when trying to preview the actual report. Error message pop up.

![image](https://user-images.githubusercontent.com/51438852/59421373-0f0afa80-8e01-11e9-9a33-5551bd8e7c18.png)

This is image when previewing the report.

![image](https://user-images.githubusercontent.com/51438852/59421663-90fb2380-8e01-11e9-89b4-d89f86d2e062.png)

**Comment by ZawZawThein** [comment]
![gl](https://user-images.githubusercontent.com/47886841/61853019-d9b5fa00-aee0-11e9-9653-6903db0021d3.png)
 
please test again.

**Comment by zeusa2000** [comment]
looks okay now.

![image](https://user-images.githubusercontent.com/51438852/61930980-fd954080-afb1-11e9-9679-257dc5163cda.png)
