### ISSUE TITLE
Ledger-> Reports and Queries -> General Ledger-> General Ledger Listing (SubLedger). Under construction.

### ISSUE THREAD

**Issue by KatrinaCagaanan** [a2000-erp-team/WEBERP#98]
![image](https://user-images.githubusercontent.com/47963355/54662492-29db1500-4b19-11e9-92fd-48ad3b6537b6.png)

**Comment by zeusa2000** [comment]
Can view now the General Ledger Listing (Sub-Ledger)report.

![image](https://user-images.githubusercontent.com/51438852/59657903-a9d65100-91d4-11e9-9095-9f11ced9c66e.png)
